-- Catalog v3 PostgreSQL baseline. Large immutable bytes live in the configured
-- blob store. Entity identifiers are UUIDv7 values generated by LibrePaper.

CREATE TABLE accounts (
    id uuid PRIMARY KEY,
    kind text NOT NULL CHECK (kind IN ('registered', 'anonymous', 'system')),
    provider text,
    provider_subject text,
    handle text NOT NULL,
    display_name text NOT NULL,
    email text,
    status text NOT NULL CHECK (status IN ('active', 'erasing', 'blocked')),
    session_generation bigint NOT NULL DEFAULT 1 CHECK (session_generation >= 1),
    preferences jsonb NOT NULL DEFAULT '{"version":1}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    last_seen_at timestamptz NOT NULL DEFAULT now(),
    CHECK ((kind = 'registered' AND provider IS NOT NULL AND provider_subject IS NOT NULL)
        OR (kind <> 'registered' AND provider IS NULL AND provider_subject IS NULL))
);
CREATE UNIQUE INDEX accounts_provider_subject
    ON accounts(provider, provider_subject) WHERE kind = 'registered';

CREATE TABLE documents (
    id uuid PRIMARY KEY,
    slug text NOT NULL UNIQUE,
    owner_id uuid NOT NULL REFERENCES accounts(id),
    ownership_mode text NOT NULL CHECK (ownership_mode IN ('owned', 'open', 'example')),
    title text NOT NULL,
    title_key text NOT NULL,
    status text NOT NULL CHECK (status IN ('active', 'deleting')),
    source_format text NOT NULL CHECK (source_format IN ('markdown','html','typst','latex','quarto')),
    main_path text NOT NULL,
    update_sequence bigint NOT NULL DEFAULT 0 CHECK (update_sequence >= 0),
    project_generation bigint NOT NULL DEFAULT 0 CHECK (project_generation >= 0),
    current_version_id uuid,
    current_publication_id uuid,
    settings jsonb NOT NULL DEFAULT '{"version":1}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    CHECK ((status = 'deleting') = (deleted_at IS NOT NULL))
);
CREATE INDEX documents_owner_updated ON documents(owner_id, updated_at DESC, id DESC);
CREATE INDEX documents_title_search ON documents(owner_id, title_key);
CREATE INDEX documents_open_updated ON documents(updated_at DESC, id DESC)
    WHERE status = 'active' AND ownership_mode = 'open';

CREATE TABLE grants (
    document_id uuid NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    account_id uuid NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    role text NOT NULL CHECK (role IN ('reader','commenter','editor')),
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (document_id, account_id)
);
CREATE INDEX grants_account ON grants(account_id, document_id);

CREATE TABLE share_links (
    id uuid PRIMARY KEY,
    document_id uuid NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    role text NOT NULL CHECK (role IN ('reader','commenter','editor')),
    token_hash bytea NOT NULL UNIQUE CHECK (octet_length(token_hash) = 32),
    label text NOT NULL DEFAULT '',
    generation bigint NOT NULL DEFAULT 1 CHECK (generation >= 1),
    created_at timestamptz NOT NULL DEFAULT now(),
    expires_at timestamptz,
    revoked_at timestamptz,
    CHECK (expires_at IS NULL OR expires_at >= created_at)
);
CREATE INDEX share_links_document ON share_links(document_id, role) WHERE revoked_at IS NULL;

CREATE TABLE annotations (
    id uuid PRIMARY KEY,
    document_id uuid NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    kind text NOT NULL CHECK (kind IN ('comment','highlight','suggestion')),
    body text NOT NULL,
    author_account_id uuid REFERENCES accounts(id),
    author_key text NOT NULL,
    author_label text NOT NULL,
    selector jsonb NOT NULL,
    context jsonb NOT NULL DEFAULT '{"version":1}'::jsonb,
    source_version_id uuid,
    source_update_sequence bigint CHECK (source_update_sequence IS NULL OR source_update_sequence >= 0),
    source_project_generation bigint CHECK (source_project_generation IS NULL OR source_project_generation >= 0),
    source_state_vector bytea,
    publication_id uuid,
    proposed_text text,
    suggestion_state text CHECK (suggestion_state IN ('proposed','accepted','rejected')),
    resolved_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK ((kind = 'suggestion' AND proposed_text IS NOT NULL AND suggestion_state IS NOT NULL)
        OR (kind <> 'suggestion' AND proposed_text IS NULL AND suggestion_state IS NULL))
);
CREATE INDEX annotations_timeline ON annotations(document_id, created_at, id);
CREATE INDEX annotations_publication_timeline
    ON annotations(document_id, publication_id, created_at, id) WHERE publication_id IS NOT NULL;

CREATE TABLE replies (
    id uuid PRIMARY KEY,
    annotation_id uuid NOT NULL REFERENCES annotations(id) ON DELETE CASCADE,
    author_account_id uuid REFERENCES accounts(id),
    author_key text NOT NULL,
    author_label text NOT NULL,
    body text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX replies_timeline ON replies(annotation_id, created_at, id);

CREATE TABLE document_assets (
    id uuid PRIMARY KEY,
    document_id uuid NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    storage_key text NOT NULL UNIQUE,
    digest bytea NOT NULL CHECK (octet_length(digest) = 32),
    byte_length bigint NOT NULL CHECK (byte_length >= 0),
    media_type text NOT NULL,
    original_name text,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (document_id, digest, byte_length)
);
CREATE INDEX document_assets_document ON document_assets(document_id, created_at, id);

CREATE TABLE document_versions (
    id uuid PRIMARY KEY,
    document_id uuid NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    sequence bigint NOT NULL CHECK (sequence >= 1),
    parent_id uuid,
    through_update_sequence bigint NOT NULL CHECK (through_update_sequence >= 0),
    project_generation bigint NOT NULL CHECK (project_generation >= 0),
    archive_key text NOT NULL UNIQUE,
    archive_encoding_version smallint NOT NULL CHECK (archive_encoding_version >= 1),
    archive_digest bytea NOT NULL CHECK (octet_length(archive_digest) = 32),
    archive_bytes bigint NOT NULL CHECK (archive_bytes >= 0),
    logical_bytes bigint NOT NULL CHECK (logical_bytes >= 0),
    reason text NOT NULL,
    label text,
    author_account_id uuid REFERENCES accounts(id),
    author_label text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (document_id, sequence),
    FOREIGN KEY (parent_id) REFERENCES document_versions(id)
);
CREATE INDEX document_versions_history ON document_versions(document_id, sequence DESC, id DESC);
CREATE INDEX document_versions_retention
    ON document_versions(document_id, created_at, sequence) WHERE label IS NULL;

CREATE TABLE publications (
    id uuid PRIMARY KEY,
    document_id uuid NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    source_version_id uuid,
    request_key text NOT NULL,
    request_digest bytea NOT NULL CHECK (octet_length(request_digest) = 32),
    manifest_key text NOT NULL UNIQUE,
    manifest_digest bytea NOT NULL CHECK (octet_length(manifest_digest) = 32),
    publisher_account_id uuid REFERENCES accounts(id),
    publisher_label text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (document_id, request_key),
    FOREIGN KEY (source_version_id) REFERENCES document_versions(id)
);
CREATE INDEX publications_document ON publications(document_id, created_at DESC, id DESC);

CREATE TABLE publication_files (
    publication_id uuid NOT NULL REFERENCES publications(id) ON DELETE CASCADE,
    path text NOT NULL,
    storage_key text NOT NULL UNIQUE,
    digest bytea NOT NULL CHECK (octet_length(digest) = 32),
    byte_length bigint NOT NULL CHECK (byte_length >= 0),
    media_type text NOT NULL,
    PRIMARY KEY (publication_id, path)
);

ALTER TABLE documents ADD CONSTRAINT documents_current_version_fk
    FOREIGN KEY (current_version_id) REFERENCES document_versions(id)
    ON DELETE SET NULL;
ALTER TABLE documents ADD CONSTRAINT documents_current_publication_fk
    FOREIGN KEY (current_publication_id) REFERENCES publications(id)
    ON DELETE SET NULL;

CREATE TABLE document_updates (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    document_id uuid NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    update_sequence bigint NOT NULL CHECK (update_sequence >= 1),
    update_bytes bytea NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (document_id, update_sequence)
);
CREATE INDEX document_updates_replay ON document_updates(document_id, update_sequence);

CREATE TABLE document_bases (
    document_id uuid PRIMARY KEY REFERENCES documents(id) ON DELETE CASCADE,
    base_id uuid NOT NULL UNIQUE,
    through_update_sequence bigint NOT NULL CHECK (through_update_sequence >= 0),
    project_generation bigint NOT NULL CHECK (project_generation >= 0),
    snapshot_key text NOT NULL UNIQUE,
    snapshot_digest bytea NOT NULL CHECK (octet_length(snapshot_digest) = 32),
    snapshot_bytes bigint NOT NULL CHECK (snapshot_bytes >= 0),
    previous_snapshot_key text,
    previous_delete_after timestamptz,
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK ((previous_snapshot_key IS NULL) = (previous_delete_after IS NULL))
);

CREATE TABLE jobs (
    id uuid PRIMARY KEY,
    kind text NOT NULL,
    document_id uuid REFERENCES documents(id) ON DELETE SET NULL,
    account_id uuid REFERENCES accounts(id) ON DELETE SET NULL,
    scope_key text NOT NULL,
    dedupe_key text,
    payload jsonb NOT NULL,
    status text NOT NULL CHECK (status IN ('queued','running','succeeded','failed','cancelled')),
    priority smallint NOT NULL DEFAULT 0,
    attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    max_attempts integer NOT NULL DEFAULT 10 CHECK (max_attempts >= 1),
    run_after timestamptz NOT NULL DEFAULT now(),
    locked_by text,
    locked_at timestamptz,
    claim_token uuid,
    last_error text,
    result jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK ((status = 'running') = (locked_by IS NOT NULL AND locked_at IS NOT NULL AND claim_token IS NOT NULL))
);
CREATE UNIQUE INDEX jobs_active_dedupe ON jobs(kind, scope_key, dedupe_key)
    WHERE dedupe_key IS NOT NULL AND status IN ('queued','running');
CREATE INDEX jobs_claim ON jobs(priority DESC, run_after, created_at)
    WHERE status = 'queued';
CREATE INDEX jobs_expired_claim ON jobs(locked_at, id) WHERE status = 'running';

CREATE TABLE maintenance_cursors (
    name text PRIMARY KEY,
    cursor text,
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE schema_metadata (
    singleton boolean PRIMARY KEY DEFAULT true CHECK (singleton),
    deployment_id uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);
