-- The LibrePaper catalogue.
--
-- One schema, one migration. Large immutable bytes live in the configured blob
-- store and the catalogue names them by key and digest. Entity identifiers are
-- UUIDv7 values generated by LibrePaper.

CREATE TABLE accounts (
    id uuid PRIMARY KEY,
    kind text NOT NULL CHECK (kind IN ('registered', 'anonymous', 'system')),
    provider text,
    provider_subject text,
    handle text NOT NULL,
    display_name text NOT NULL,
    email text,
    status text NOT NULL CHECK (status IN ('active', 'erasing', 'blocked')),
    session_generation bigint NOT NULL DEFAULT 1 CHECK (session_generation >= 1),
    preferences jsonb NOT NULL DEFAULT '{"version":1}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    last_seen_at timestamptz NOT NULL DEFAULT now(),
    CHECK ((kind = 'registered' AND provider IS NOT NULL AND provider_subject IS NOT NULL)
        OR (kind <> 'registered' AND provider IS NULL AND provider_subject IS NULL))
);
CREATE UNIQUE INDEX accounts_provider_subject
    ON accounts(provider, provider_subject) WHERE kind = 'registered';

CREATE TABLE documents (
    id uuid PRIMARY KEY,
    slug text NOT NULL UNIQUE,
    owner_id uuid NOT NULL REFERENCES accounts(id),
    ownership_mode text NOT NULL CHECK (ownership_mode IN ('owned', 'open', 'example')),
    title text NOT NULL,
    status text NOT NULL CHECK (status IN ('active', 'deleting')),
    source_format text NOT NULL CHECK (source_format IN ('markdown','html','typst','latex','quarto')),
    main_path text NOT NULL,
    update_sequence bigint NOT NULL DEFAULT 0 CHECK (update_sequence >= 0),
    project_generation bigint NOT NULL DEFAULT 0 CHECK (project_generation >= 0),
    current_version_id uuid,
    current_bundle_id uuid,
    settings jsonb NOT NULL DEFAULT '{"version":1}'::jsonb,
    -- Hard collaboration admission is an O(1) decision taken under the document
    -- row lock, so the size of the backlog is kept on the row rather than
    -- counted out of document_updates.
    uncompacted_update_count bigint NOT NULL DEFAULT 0
        CHECK (uncompacted_update_count >= 0),
    uncompacted_update_bytes bigint NOT NULL DEFAULT 0
        CHECK (uncompacted_update_bytes >= 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    CHECK ((status = 'deleting') = (deleted_at IS NOT NULL))
);

-- Both listings page by (updated_at, id): one scoped to an owner, one across
-- every active document. The owner index is deliberately unpartitioned, since
-- account erasure counts an owner's documents without a status filter.
CREATE INDEX documents_owner_updated ON documents(owner_id, updated_at DESC, id DESC);
CREATE INDEX documents_active_updated ON documents(updated_at DESC, id DESC)
    WHERE status = 'active';

-- PostgreSQL indexes the referenced side of a foreign key, never the
-- referencing side, so without these a version delete scans this table once per
-- constraint. Version retention deletes versions inline in the transaction that
-- commits a new one, which puts that scan on the write path.
CREATE INDEX documents_current_version ON documents(current_version_id)
    WHERE current_version_id IS NOT NULL;
CREATE INDEX documents_current_bundle ON documents(current_bundle_id)
    WHERE current_bundle_id IS NOT NULL;

CREATE TABLE grants (
    document_id uuid NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    account_id uuid NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    role text NOT NULL CHECK (role IN ('reader','commenter','editor')),
    created_at timestamptz NOT NULL DEFAULT now(),
    -- The link this grant came through, when it came through one. Part of the
    -- authorization decision: revoking a link revokes what it handed out.
    source_link_hash bytea CHECK (source_link_hash IS NULL OR octet_length(source_link_hash) = 32),
    PRIMARY KEY (document_id, account_id)
);
CREATE INDEX grants_account ON grants(account_id, document_id);

CREATE TABLE share_links (
    id uuid PRIMARY KEY,
    document_id uuid NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    role text NOT NULL CHECK (role IN ('reader','commenter','editor')),
    token_hash bytea NOT NULL UNIQUE CHECK (octet_length(token_hash) = 32),
    label text NOT NULL DEFAULT '',
    generation bigint NOT NULL DEFAULT 1 CHECK (generation >= 1),
    -- The raw key of the URL, sealed with the deployment's session key, which
    -- lives in the secrets directory and never here. A copy of this database on
    -- its own yields no working link: the digest above does the whole job of
    -- admitting a caller, and this column only lets the server that owns the
    -- secret say the URL again, so the owner can copy a link they already made.
    sealed_token bytea NOT NULL DEFAULT ''::bytea,
    -- Part of the rate-limit decision for a commenter arriving through a link.
    comment_budget bigint CHECK (comment_budget IS NULL OR comment_budget >= 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    expires_at timestamptz,
    revoked_at timestamptz,
    CHECK (expires_at IS NULL OR expires_at >= created_at)
);
CREATE INDEX share_links_document ON share_links(document_id, role) WHERE revoked_at IS NULL;

-- What one person has done with one document, as distinct from what they may
-- do to it.
--
-- `grants` says what a person is allowed to do, and exists only for documents
-- somebody was given. Favouriting and opening are neither permissions nor
-- gifts: you favourite your own work, and the document you opened most recently
-- is usually one nobody had to share with you. One table for both, because they
-- are the same shape -- a person, a document, a timestamp -- and a listing that
-- shows Favorites sorted by when you last opened them would otherwise join the
-- same pair of ids twice.
CREATE TABLE document_marks (
    account_id uuid NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    document_id uuid NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    -- When it was favourited, not whether: "your favourites, most recent
    -- first" is the order a list of them wants, and a boolean cannot answer
    -- it. NULL is a document this person has opened but not starred.
    favorited_at timestamptz,
    -- The last time this person opened it. NULL is a document they have
    -- starred without opening -- rare, but reachable: a project shared with
    -- you can be starred from the listing before you ever go in.
    opened_at timestamptz,
    PRIMARY KEY (account_id, document_id),
    -- A row that says neither is a row that says nothing. Un-favouriting
    -- something never opened deletes the row rather than blanking the column,
    -- so the table holds marks and not the debris of marks.
    CHECK (favorited_at IS NOT NULL OR opened_at IS NOT NULL)
);

-- One index per destination in the listing's rail, both partial: a person's
-- recently-opened projects are a small suffix of everything they have ever
-- opened, and their favourites a small subset of that.
CREATE INDEX document_marks_favorites ON document_marks(account_id, favorited_at DESC)
    WHERE favorited_at IS NOT NULL;
CREATE INDEX document_marks_recent ON document_marks(account_id, opened_at DESC)
    WHERE opened_at IS NOT NULL;

-- A comment is a place in the source, not a quotation.
--
-- What a comment is about is a range: the file (by its stable Loro id, never
-- its name), the UTF-16 offsets in it, and the checkpoint those offsets are
-- offsets into. It is written once, by the server, from the words a client
-- sent, and no later event edits it. Where that passage has got to since is a
-- separate row in `annotation_live_state`, which is a cache.
--
-- The rendered words stay, in their own columns, under names that say what they
-- are: what the comment looked like where it was made -- worth showing a
-- person, never resolved through.
CREATE TABLE annotations (
    id uuid PRIMARY KEY,
    document_id uuid NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    kind text NOT NULL CHECK (kind IN ('comment','highlight','suggestion')),
    body text NOT NULL,
    author_account_id uuid REFERENCES accounts(id),
    author_key text NOT NULL,
    author_label text NOT NULL,
    color text,

    -- The rendered page this remark was made against, when it was made by a
    -- reader rather than in the editor.
    bundle_id uuid,

    checkpoint_id text NOT NULL,
    target_kind text NOT NULL,
    file_id text,
    start_utf16 integer,
    end_utf16 integer,
    start_side text,
    end_side text,
    exact text,
    prefix text,
    suffix text,

    rendered_exact text NOT NULL DEFAULT '',
    rendered_prefix text NOT NULL DEFAULT '',
    rendered_suffix text NOT NULL DEFAULT '',
    rendered_position_utf16 integer,

    resolved_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT annotations_target_kind CHECK (target_kind IN ('source_text', 'document')),
    -- A passage carries a range and its evidence; a remark about the document
    -- as a whole carries none of it. Neither can be half filled in.
    CONSTRAINT annotations_source_text_target CHECK (
        (target_kind = 'source_text'
            AND file_id IS NOT NULL
            AND start_utf16 IS NOT NULL AND start_utf16 >= 0
            AND end_utf16 IS NOT NULL AND end_utf16 >= start_utf16
            AND start_side IN ('left', 'right')
            AND end_side IN ('left', 'right')
            AND exact IS NOT NULL AND prefix IS NOT NULL AND suffix IS NOT NULL)
        OR
        (target_kind = 'document'
            AND file_id IS NULL
            AND start_utf16 IS NULL AND end_utf16 IS NULL
            AND start_side IS NULL AND end_side IS NULL
            AND exact IS NULL AND prefix IS NULL AND suffix IS NULL)
    )
);
CREATE INDEX annotations_timeline ON annotations(document_id, created_at, id);
CREATE INDEX annotations_bundle_timeline
    ON annotations(document_id, bundle_id, created_at, id) WHERE bundle_id IS NOT NULL;
-- Finding every comment on a file, which is what a resolution pass walks.
CREATE INDEX annotations_source_file ON annotations(document_id, file_id, created_at, id)
    WHERE file_id IS NOT NULL;

-- Where each comment's passage is now, as last resolved. Every column here is
-- replaceable: the row is keyed by the checkpoint it was computed against and
-- is rewritten whenever the document moves. Nothing reads it to find out what a
-- comment is about, so deleting all of it costs one recomputation and loses
-- nothing.
--
-- The cursors are Loro's own anchors, captured when the comment was made and
-- replaced by whatever Loro hands back on a later resolution. They live here,
-- and not beside the range above, for exactly that reason.
CREATE TABLE annotation_live_state (
    annotation_id uuid PRIMARY KEY REFERENCES annotations(id) ON DELETE CASCADE,
    checkpoint_id text,
    status text NOT NULL DEFAULT 'unresolved'
        CHECK (status IN ('exact','modified','ambiguous','deleted','unresolved')),
    start_cursor bytea,
    end_cursor bytea,
    cursor_format text,
    resolved_start_utf16 integer,
    resolved_end_utf16 integer,
    diagnostic text,
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK ((start_cursor IS NULL) = (end_cursor IS NULL)),
    CHECK ((start_cursor IS NULL) OR cursor_format IS NOT NULL)
);

CREATE TABLE replies (
    id uuid PRIMARY KEY,
    annotation_id uuid NOT NULL REFERENCES annotations(id) ON DELETE CASCADE,
    author_account_id uuid REFERENCES accounts(id),
    author_key text NOT NULL,
    author_label text NOT NULL,
    body text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX replies_timeline ON replies(annotation_id, created_at, id);

-- Content-addressed and unique per (document_id, digest, byte_length). Nothing
-- deletes from this table, and the orphan sweeper treats every key it names as
-- live, which is what lets a bundle reference a figure rather than copy it.
CREATE TABLE document_assets (
    id uuid PRIMARY KEY,
    document_id uuid NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    storage_key text NOT NULL UNIQUE,
    digest bytea NOT NULL CHECK (octet_length(digest) = 32),
    byte_length bigint NOT NULL CHECK (byte_length >= 0),
    media_type text NOT NULL,
    original_name text,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (document_id, digest, byte_length)
);

CREATE TABLE document_versions (
    id uuid PRIMARY KEY,
    document_id uuid NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    sequence bigint NOT NULL CHECK (sequence >= 1),
    -- Provenance only. Bounded version retention deletes ancestors, so this
    -- link must not be able to hold one alive.
    parent_id uuid,
    through_update_sequence bigint NOT NULL CHECK (through_update_sequence >= 0),
    project_generation bigint NOT NULL CHECK (project_generation >= 0),

    -- A version's archive is named by the digest of its own bytes, so two
    -- versions holding the same document name the same object and it is stored
    -- once. The key is a reference, not a possession, and is not unique here.
    archive_key text NOT NULL,
    archive_encoding_version smallint NOT NULL CHECK (archive_encoding_version >= 1),
    archive_digest bytea NOT NULL CHECK (octet_length(archive_digest) = 32),
    archive_bytes bigint NOT NULL CHECK (archive_bytes >= 0),
    logical_bytes bigint NOT NULL CHECK (logical_bytes >= 0),

    -- What this version holds, as a document rather than as an encoding: the
    -- digest of its canonical file tree. The archive is one encoding of that
    -- tree, and an encoder change would rename an unchanged document. Without
    -- this a server could not tell that the live document still says exactly
    -- what the newest version says, and would write a duplicate archive every
    -- time a room was opened and closed.
    tree_digest bytea CHECK (tree_digest IS NULL OR octet_length(tree_digest) = 32),

    -- The paths whose contents differ from the parent version's, recorded once,
    -- when the version is written and both trees are in hand. It is what lets
    -- the history panel scope a timeline to the file being edited without
    -- opening two trees for every row. NULL means the question was never
    -- answered for this version, which readers must not mistake for "nothing".
    changed_paths text[],

    -- How many files this version holds, written down at the one moment the
    -- file list is in hand. A version's files live inside its archive, which is
    -- an opaque blob to SQL, and the project listing wants the number without
    -- fetching and decoding anything. NULL is "not known", rendered as "--".
    file_count integer CHECK (file_count IS NULL OR file_count >= 0),

    reason text NOT NULL,
    label text,
    author_account_id uuid REFERENCES accounts(id),
    author_label text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (document_id, sequence),
    FOREIGN KEY (parent_id) REFERENCES document_versions(id) ON DELETE SET NULL
);
CREATE INDEX document_versions_retention
    ON document_versions(document_id, created_at, sequence) WHERE label IS NULL;
-- Storage accounting looks up siblings by key on every version write and delete.
CREATE INDEX document_versions_archive_key ON document_versions(archive_key);
CREATE INDEX document_versions_parent ON document_versions(parent_id)
    WHERE parent_id IS NOT NULL;

-- What a reader is shown: the rendered HTML and the display assets it
-- references, named by their digests, swapped in whole. Nobody presses Publish;
-- the bundle is rebuilt whenever the source goes quiet.
--
-- A retired bundle keeps its row forever and releases its files. The row is
-- what `room::published_source` reads to turn a reader's quoted words into a
-- range of the source -- somebody still reading the page they opened must be
-- able to comment on it -- and it is what spares that source version from
-- history pruning. Its files are unreachable by any route once it is no longer
-- current, so `manifest_key` must be able to say that it holds nothing.
CREATE TABLE bundles (
    id uuid PRIMARY KEY,
    document_id uuid NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    source_version_id uuid,
    request_key text NOT NULL,
    request_digest bytea NOT NULL CHECK (octet_length(request_digest) = 32),
    manifest_key text UNIQUE,
    manifest_digest bytea NOT NULL CHECK (octet_length(manifest_digest) = 32),
    -- Whoever's browser did the rendering. The renderers are pinned WebAssembly
    -- that runs client-side; no server here can produce a page.
    rendered_by_account_id uuid REFERENCES accounts(id),
    rendered_by_label text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (document_id, request_key),
    FOREIGN KEY (source_version_id) REFERENCES document_versions(id) ON DELETE SET NULL
);
CREATE INDEX bundles_source_version ON bundles(source_version_id)
    WHERE source_version_id IS NOT NULL;

-- A bundle owns its rendering. It does not own the figures in it: `storage_key`
-- is a reference rather than a possession, and is not unique here.
CREATE TABLE bundle_files (
    bundle_id uuid NOT NULL REFERENCES bundles(id) ON DELETE CASCADE,
    path text NOT NULL,
    storage_key text NOT NULL,
    digest bytea NOT NULL CHECK (octet_length(digest) = 32),
    byte_length bigint NOT NULL CHECK (byte_length >= 0),
    media_type text NOT NULL,
    PRIMARY KEY (bundle_id, path)
);
-- Storage accounting looks up siblings by key on every bundle file write and
-- delete, and the orphan sweeper reads this column too.
CREATE INDEX bundle_files_storage_key ON bundle_files(storage_key);

ALTER TABLE documents ADD CONSTRAINT documents_current_version_fk
    FOREIGN KEY (current_version_id) REFERENCES document_versions(id)
    ON DELETE SET NULL;
ALTER TABLE documents ADD CONSTRAINT documents_current_bundle_fk
    FOREIGN KEY (current_bundle_id) REFERENCES bundles(id)
    ON DELETE SET NULL;

-- The collaboration update log: a queue, not a history. Once a base holds these
-- operations the rows are deleted, so the table is bounded by the compaction
-- threshold. (document_id, update_sequence) is the whole identity -- ordering,
-- replay and compaction all address a row by it -- so it is the primary key and
-- this highest-write table carries exactly one btree.
CREATE TABLE document_updates (
    document_id uuid NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    update_sequence bigint NOT NULL CHECK (update_sequence >= 1),
    update_bytes bytea NOT NULL,
    -- The Loro frontier this update reached, so a moment on the timeline can be
    -- turned back into the document as it stood then.
    frontier bytea NOT NULL DEFAULT ''::bytea,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (document_id, update_sequence)
);

-- When a document was worked on, kept past the compaction that deletes the
-- updates it was measured from, and anchored so a reader can go there.
--
-- `created_at` on an update is the only trustworthy clock the system has -- it
-- is stamped server-side at admission, unlike a Loro change timestamp, which is
-- the client's and is forced monotonic -- so it is aggregated into buckets here
-- before those rows are deleted rather than lost with them.
--
-- One row per document, bucket and peer, not one per write: a million
-- keystrokes is a few thousand minutes. `peer` is in the key so per-author
-- activity needs no migration later; nothing records an author on an update
-- today, and those rows carry the empty string.
--
-- `state_bytes` is the largest encoded history seen in the bucket, not the
-- weight of the edits in it: a persisted row is the whole operation history
-- (`session::encode_state`), so its size measures the document, and the work
-- done in a bucket is the difference between consecutive buckets. `changes`
-- counts persistence cycles -- roughly one per couple of seconds in which
-- somebody was typing -- and is the honest count of "was this minute worked
-- in". The anchor is a Loro frontier rather than an update sequence, because
-- the sequence means nothing once the rows behind it are gone.
CREATE TABLE document_activity (
    document_id uuid NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    bucket timestamptz NOT NULL,
    peer text NOT NULL,
    changes integer NOT NULL CHECK (changes >= 0),
    state_bytes bigint NOT NULL CHECK (state_bytes >= 0),
    frontier bytea NOT NULL,
    PRIMARY KEY (document_id, bucket, peer)
);

CREATE TABLE document_bases (
    document_id uuid PRIMARY KEY REFERENCES documents(id) ON DELETE CASCADE,
    base_id uuid NOT NULL UNIQUE,
    through_update_sequence bigint NOT NULL CHECK (through_update_sequence >= 0),
    project_generation bigint NOT NULL CHECK (project_generation >= 0),
    snapshot_key text NOT NULL UNIQUE,
    snapshot_digest bytea NOT NULL CHECK (octet_length(snapshot_digest) = 32),
    snapshot_bytes bigint NOT NULL CHECK (snapshot_bytes >= 0),
    previous_snapshot_key text,
    previous_delete_after timestamptz,
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK ((previous_snapshot_key IS NULL) = (previous_delete_after IS NULL))
);

-- A proposed change is a branch, and its status lives here rather than in the
-- document. A client that can write to the document can write to anything
-- stored in it, including the record that says whether its own edit was
-- approved; keeping the decision here is what makes it server-owned.
--
-- The branch itself is stored here too, as the operations since its fork. A
-- base is large, long-lived and read on cold start; a branch is none of those.
-- More decisively, accepting a proposal has to write the decision and the
-- resulting document update together or not at all, and one transaction over
-- one store is how that is actually achieved.
CREATE TABLE document_proposals (
    id uuid PRIMARY KEY,
    document_id uuid NOT NULL REFERENCES documents(id) ON DELETE CASCADE,

    -- Who opened it, for attribution in the UI. The authorship that matters for
    -- contract 4 is not this: it is carried by the operations themselves, and
    -- survives a partial accept because the branch is merged whole.
    author text NOT NULL,

    -- The peer that wrote the branch. Kept so the room can tell a proposal's own
    -- operations from everyone else's without decoding the blob.
    author_peer bigint NOT NULL,

    -- Encoded frontiers. `base` is where the branch forked; `tip` is where it
    -- had reached when it was last updated. Review is the diff between them, and
    -- a decision names the tip it was computed against so that a decision made
    -- against a stale tip can be refused rather than applied to text that has
    -- since changed underneath the reviewer.
    base_frontiers bytea NOT NULL,
    tip_frontiers bytea NOT NULL,

    -- The branch: Loro operations since the fork, not a whole document.
    branch_bytes bytea NOT NULL,

    -- `pending` until every hunk has been decided; then `resolved`. A proposal
    -- that the document has moved past without deciding is `superseded`.
    -- Whether the change landed is a property of its hunks, not of the proposal
    -- -- accepting half of one is the ordinary case, so there is no single
    -- accepted/declined answer to record here.
    status text NOT NULL CHECK (status IN ('pending', 'resolved', 'superseded')),

    -- Set when the proposal resolves, together in one write with the update that
    -- carried its accepted hunks into the document.
    resolved_by text,
    resolved_at timestamptz,

    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

-- The open proposals for a document, which is what a joining client asks for and
-- what the room broadcasts after every decision.
CREATE INDEX document_proposals_open ON document_proposals(document_id, status);

-- One row per decision, because a reviewer decides hunks and not proposals.
--
-- A hunk is named by its index in the diff of a named tip against a named base
-- (§5.2). That identity is deliberately free of any offset: the server counts
-- hunks in code points and the browser counts them in UTF-16, so an index is the
-- one way to name a hunk that means the same thing on both sides. It is stable
-- only against the tip it was computed from, which is why that tip is recorded
-- beside it.
CREATE TABLE document_proposal_hunks (
    proposal_id uuid NOT NULL REFERENCES document_proposals(id) ON DELETE CASCADE,
    hunk_index integer NOT NULL CHECK (hunk_index >= 0),
    accepted boolean NOT NULL,
    decided_by text NOT NULL,
    decided_at timestamptz NOT NULL DEFAULT now(),

    -- The tip this decision was computed against. A decision whose tip is no
    -- longer the proposal's tip was made about a diff that no longer exists.
    decided_against bytea NOT NULL,

    -- A reviewer may say why, and declining is where that matters most.
    note text,

    PRIMARY KEY (proposal_id, hunk_index)
);

CREATE TABLE jobs (
    id uuid PRIMARY KEY,
    kind text NOT NULL,
    document_id uuid REFERENCES documents(id) ON DELETE SET NULL,
    account_id uuid REFERENCES accounts(id) ON DELETE SET NULL,
    scope_key text NOT NULL,
    dedupe_key text,
    payload jsonb NOT NULL,
    status text NOT NULL CHECK (status IN ('queued','running','succeeded','failed','cancelled')),
    priority smallint NOT NULL DEFAULT 0,
    attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    max_attempts integer NOT NULL DEFAULT 10 CHECK (max_attempts >= 1),
    run_after timestamptz NOT NULL DEFAULT now(),
    locked_by text,
    locked_at timestamptz,
    claim_token uuid,
    last_error text,
    result jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK ((status = 'running') = (locked_by IS NOT NULL AND locked_at IS NOT NULL AND claim_token IS NOT NULL))
);
CREATE UNIQUE INDEX jobs_active_dedupe ON jobs(kind, scope_key, dedupe_key)
    WHERE dedupe_key IS NOT NULL AND status IN ('queued','running');
CREATE INDEX jobs_claim ON jobs(priority DESC, run_after, created_at)
    WHERE status = 'queued';
CREATE INDEX jobs_expired_claim ON jobs(locked_at, id) WHERE status = 'running';
-- The third pass over this table deletes finished jobs oldest-first.
CREATE INDEX jobs_terminal_cleanup ON jobs(updated_at, id)
    WHERE status IN ('succeeded', 'failed', 'cancelled');
CREATE INDEX jobs_document ON jobs(document_id) WHERE document_id IS NOT NULL;
CREATE INDEX jobs_account ON jobs(account_id) WHERE account_id IS NOT NULL;

CREATE TABLE maintenance_cursors (
    name text PRIMARY KEY,
    cursor text,
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE schema_metadata (
    singleton boolean PRIMARY KEY DEFAULT true CHECK (singleton),
    deployment_id uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

-- Durable deployment-scoped payloads. The server owns each value's JSON schema
-- and replaces it atomically at each checkpoint.
CREATE TABLE server_runtime_state (
    name text PRIMARY KEY,
    value jsonb NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now()
);

-- Deployment storage counts objects, not references.
--
-- The counter is the number of bytes actually held in the blob store. Archives
-- and bundle files are named by digest and shared, so a row naming an object
-- some other row already names adds no bytes, and refunding on its delete would
-- decrement the counter for bytes that are still held -- a counter that drifts
-- below the truth eventually admits writes the deployment has no room for.
--
-- So each side asks the same question -- is this row the only one naming this
-- object? -- and moves the counter only then. It is asked in an AFTER trigger,
-- where on INSERT the new row is already visible and must not count itself, and
-- on DELETE the old row is already gone.
CREATE TABLE storage_usage (
    singleton boolean PRIMARY KEY DEFAULT true CHECK (singleton),
    bytes bigint NOT NULL CHECK (bytes >= 0)
);
INSERT INTO storage_usage(bytes) VALUES (0);

-- An asset is unique per (document_id, digest, byte_length) and nothing deletes
-- from that table, so it is always the sole owner of its object.
CREATE FUNCTION adjust_asset_storage_usage() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    UPDATE storage_usage SET bytes = bytes + CASE WHEN TG_OP='INSERT' THEN NEW.byte_length ELSE -OLD.byte_length END;
    IF TG_OP = 'DELETE' THEN RETURN OLD; ELSE RETURN NEW; END IF;
END
$$;

CREATE FUNCTION adjust_version_storage_usage() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    shared boolean;
BEGIN
    IF TG_OP = 'INSERT' THEN
        SELECT EXISTS(SELECT 1 FROM document_versions
                      WHERE archive_key = NEW.archive_key AND id IS DISTINCT FROM NEW.id)
          INTO shared;
        IF NOT shared THEN
            UPDATE storage_usage SET bytes = bytes + NEW.archive_bytes;
        END IF;
        RETURN NEW;
    ELSE
        SELECT EXISTS(SELECT 1 FROM document_versions
                      WHERE archive_key = OLD.archive_key AND id IS DISTINCT FROM OLD.id)
          INTO shared;
        IF NOT shared THEN
            UPDATE storage_usage SET bytes = bytes - OLD.archive_bytes;
        END IF;
        RETURN OLD;
    END IF;
END
$$;

-- A bundle file has no id -- its key is (bundle_id, path) -- so that pair is
-- what distinguishes a row from its siblings here. A figure shared with
-- `document_assets` is never the only reference, so it is counted there and
-- never again here.
CREATE FUNCTION adjust_bundle_file_storage_usage() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    shared boolean;
BEGIN
    IF TG_OP = 'INSERT' THEN
        SELECT EXISTS(SELECT 1 FROM document_assets WHERE storage_key = NEW.storage_key)
            OR EXISTS(SELECT 1 FROM bundle_files
                      WHERE storage_key = NEW.storage_key
                        AND (bundle_id, path) IS DISTINCT FROM (NEW.bundle_id, NEW.path))
          INTO shared;
        IF NOT shared THEN
            UPDATE storage_usage SET bytes = bytes + NEW.byte_length;
        END IF;
        RETURN NEW;
    ELSE
        SELECT EXISTS(SELECT 1 FROM document_assets WHERE storage_key = OLD.storage_key)
            OR EXISTS(SELECT 1 FROM bundle_files
                      WHERE storage_key = OLD.storage_key
                        AND (bundle_id, path) IS DISTINCT FROM (OLD.bundle_id, OLD.path))
          INTO shared;
        IF NOT shared THEN
            UPDATE storage_usage SET bytes = bytes - OLD.byte_length;
        END IF;
        RETURN OLD;
    END IF;
END
$$;

CREATE TRIGGER document_assets_storage_usage AFTER INSERT OR DELETE ON document_assets
    FOR EACH ROW EXECUTE FUNCTION adjust_asset_storage_usage();
CREATE TRIGGER document_versions_storage_usage AFTER INSERT OR DELETE ON document_versions
    FOR EACH ROW EXECUTE FUNCTION adjust_version_storage_usage();
CREATE TRIGGER bundle_files_storage_usage AFTER INSERT OR DELETE ON bundle_files
    FOR EACH ROW EXECUTE FUNCTION adjust_bundle_file_storage_usage();
