-- The LibrePaper catalogue.
--
-- One schema, one migration. Large immutable bytes live in the configured blob
-- store and the catalogue names them by key and digest. Entity identifiers are
-- UUIDv7 values generated by LibrePaper.
--
-- The shape of this file follows from SPEC-server-is-a-log: the server stores
-- and forwards source bytes and reads only their headers to do so. So there is
-- one append-only log per document (`document_updates`), one compaction base
-- under it (`document_bases`), and relational rows whose meaning depends on
-- the source name the row that made their evidence durable. There is no
-- revision counter, no receipt table, no job queue, no rendered-bundle table
-- and no version table: each of those existed to hold something the server no
-- longer claims to know.
--
-- One deliberate departure from that spec: it lists `schema_metadata` among
-- the tables kept, and this file does not have it. The table held a single
-- `deployment_id` that nothing in the tree ever wrote and nothing ever read,
-- and that column had no default, so no row could ever exist in it. It was
-- listed as kept because the cutover did not change it, not because anything
-- needs it.

CREATE TABLE accounts (
    id uuid PRIMARY KEY,
    kind text NOT NULL CHECK (kind IN ('registered', 'anonymous', 'system')),
    provider text,
    provider_subject text,
    handle text NOT NULL,
    display_name text NOT NULL,
    email text,
    status text NOT NULL CHECK (status IN ('active', 'erasing', 'blocked')),
    session_generation bigint NOT NULL DEFAULT 1 CHECK (session_generation >= 1),
    preferences jsonb NOT NULL DEFAULT '{"version":1}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    last_seen_at timestamptz NOT NULL DEFAULT now(),
    CHECK ((kind = 'registered' AND provider IS NOT NULL AND provider_subject IS NOT NULL)
        OR (kind <> 'registered' AND provider IS NULL AND provider_subject IS NULL))
);
CREATE UNIQUE INDEX accounts_provider_subject
    ON accounts(provider, provider_subject) WHERE kind = 'registered';

CREATE TABLE documents (
    id uuid PRIMARY KEY,
    slug text NOT NULL UNIQUE,
    owner_id uuid NOT NULL REFERENCES accounts(id),
    ownership_mode text NOT NULL CHECK (ownership_mode IN ('owned', 'open', 'example')),
    title text NOT NULL,
    status text NOT NULL CHECK (status IN ('active', 'deleting')),
    source_format text NOT NULL CHECK (source_format IN ('markdown','html','typst','latex','quarto')),
    main_path text NOT NULL,
    -- The head row of this document's log. The sequencer loads it on
    -- admission and advances it under the document row lock on every flush.
    -- It identifies a row and nothing else: what state the log holds is the
    -- version vector on that row.
    update_sequence bigint NOT NULL DEFAULT 0 CHECK (update_sequence >= 0),
    settings jsonb NOT NULL DEFAULT '{"version":1}'::jsonb,
    -- Compaction admission is an O(1) decision taken under the document row
    -- lock, so the size of the backlog is kept on the row rather than counted
    -- out of document_updates.
    uncompacted_update_count bigint NOT NULL DEFAULT 0
        CHECK (uncompacted_update_count >= 0),
    uncompacted_update_bytes bigint NOT NULL DEFAULT 0
        CHECK (uncompacted_update_bytes >= 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    CHECK ((status = 'deleting') = (deleted_at IS NOT NULL))
);

-- Both listings page by (updated_at, id): one scoped to an owner, one across
-- every active document. The owner index is deliberately unpartitioned, since
-- account erasure counts an owner's documents without a status filter.
CREATE INDEX documents_owner_updated ON documents(owner_id, updated_at DESC, id DESC);
CREATE INDEX documents_active_updated ON documents(updated_at DESC, id DESC)
    WHERE status = 'active';
-- The startup scan for documents whose backlog is over the compaction
-- threshold (§8.6). Durable state, not a queue row, is what survives restart.
CREATE INDEX documents_compaction_due ON documents(id)
    WHERE status = 'active'
      AND (uncompacted_update_count >= 100 OR uncompacted_update_bytes >= 16777216);
CREATE INDEX documents_deleting ON documents(id) WHERE status = 'deleting';

CREATE TABLE grants (
    document_id uuid NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    account_id uuid NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    role text NOT NULL CHECK (role IN ('reader','commenter','editor')),
    created_at timestamptz NOT NULL DEFAULT now(),
    -- The link this grant came through, when it came through one. Part of the
    -- authorization decision: revoking a link revokes what it handed out.
    source_link_hash bytea CHECK (source_link_hash IS NULL OR octet_length(source_link_hash) = 32),
    PRIMARY KEY (document_id, account_id)
);
CREATE INDEX grants_account ON grants(account_id, document_id);

CREATE TABLE share_links (
    id uuid PRIMARY KEY,
    document_id uuid NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    role text NOT NULL CHECK (role IN ('reader','commenter','editor')),
    token_hash bytea NOT NULL UNIQUE CHECK (octet_length(token_hash) = 32),
    label text NOT NULL DEFAULT '',
    generation bigint NOT NULL DEFAULT 1 CHECK (generation >= 1),
    -- The raw key of the URL, sealed with the deployment's session key, which
    -- lives in the secrets directory and never here. A copy of this database on
    -- its own yields no working link: the digest above does the whole job of
    -- admitting a caller, and this column only lets the server that owns the
    -- secret say the URL again, so the owner can copy a link they already made.
    sealed_token bytea NOT NULL DEFAULT ''::bytea,
    -- Part of the rate-limit decision for a commenter arriving through a link.
    comment_budget bigint CHECK (comment_budget IS NULL OR comment_budget >= 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    expires_at timestamptz,
    revoked_at timestamptz,
    CHECK (expires_at IS NULL OR expires_at >= created_at)
);
CREATE INDEX share_links_document ON share_links(document_id, role) WHERE revoked_at IS NULL;

-- What one person has done with one document, as distinct from what they may
-- do to it.
--
-- `grants` says what a person is allowed to do, and exists only for documents
-- somebody was given. Favouriting and opening are neither permissions nor
-- gifts: you favourite your own work, and the document you opened most recently
-- is usually one nobody had to share with you. One table for both, because they
-- are the same shape -- a person, a document, a timestamp -- and a listing that
-- shows Favorites sorted by when you last opened them would otherwise join the
-- same pair of ids twice.
CREATE TABLE document_marks (
    account_id uuid NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    document_id uuid NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    -- When it was favourited, not whether: "your favourites, most recent
    -- first" is the order a list of them wants, and a boolean cannot answer
    -- it. NULL is a document this person has opened but not starred.
    favorited_at timestamptz,
    -- The last time this person opened it. NULL is a document they have
    -- starred without opening -- rare, but reachable: a project shared with
    -- you can be starred from the listing before you ever go in.
    opened_at timestamptz,
    PRIMARY KEY (account_id, document_id),
    -- A row that says neither is a row that says nothing. Un-favouriting
    -- something never opened deletes the row rather than blanking the column,
    -- so the table holds marks and not the debris of marks.
    CHECK (favorited_at IS NOT NULL OR opened_at IS NOT NULL)
);

-- One index per destination in the listing's rail, both partial: a person's
-- recently-opened projects are a small suffix of everything they have ever
-- opened, and their favourites a small subset of that.
CREATE INDEX document_marks_favorites ON document_marks(account_id, favorited_at DESC)
    WHERE favorited_at IS NOT NULL;
CREATE INDEX document_marks_recent ON document_marks(account_id, opened_at DESC)
    WHERE opened_at IS NOT NULL;

-- The collaboration log: framed batches, appended and never updated.
--
-- One row is one flush: the buffer as it stood, framed so that replay can hand
-- each batch back to `LoroDoc::import_batch` with the attribution it arrived
-- with (§4.2.1). `vector` is the version vector the log covers through this
-- row, merged from the batches' own headers -- no document is consulted to
-- write it, and because causal gaps are refused at ingest it is an exact
-- description of what the log holds.
--
-- (document_id, update_sequence) is the whole identity -- ordering, join and
-- compaction all address a row by it -- so it is the primary key and this
-- highest-write table carries exactly one btree.
CREATE TABLE document_updates (
    document_id uuid NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    update_sequence bigint NOT NULL CHECK (update_sequence >= 1),
    update_bytes bytea NOT NULL,
    vector bytea NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (document_id, update_sequence)
);

CREATE TABLE document_bases (
    document_id uuid PRIMARY KEY REFERENCES documents(id) ON DELETE CASCADE,
    base_id uuid NOT NULL UNIQUE,
    through_update_sequence bigint NOT NULL CHECK (through_update_sequence >= 0),
    -- The version vector this base covers, proved against the snapshot's own
    -- header before the rows behind it were deleted (§8.4 step 4).
    vector bytea NOT NULL DEFAULT ''::bytea,
    snapshot_key text NOT NULL UNIQUE,
    snapshot_digest bytea NOT NULL CHECK (octet_length(snapshot_digest) = 32),
    snapshot_bytes bigint NOT NULL CHECK (snapshot_bytes >= 0),
    updated_at timestamptz NOT NULL DEFAULT now()
);

-- The bases compaction has replaced, kept readable for seven days so a reader
-- mid-download is not cut off (§8.4 step 5).
--
-- Rows, not a pair of columns on `document_bases`, because that table holds
-- exactly one row per document while compaction fires every 100 updates or
-- 16 MiB: an actively edited document supersedes a base once or twice a day,
-- so a single predecessor slot is overwritten several times before the grace
-- expires and every base but the newest is left in the object store with
-- nothing naming it. `snapshot_key` is the primary key so scheduling the same
-- blob twice is idempotent, and the cascade is what stops a deleted document
-- from stranding rows that name blobs its deletion already removed.
CREATE TABLE superseded_bases (
    snapshot_key text PRIMARY KEY,
    document_id uuid NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    delete_after timestamptz NOT NULL
);

CREATE INDEX superseded_bases_due ON superseded_bases (delete_after);
CREATE INDEX superseded_bases_document ON superseded_bases (document_id);

-- A comment is a place in the source, not a quotation.
--
-- What a comment is about is a range: the file (by its stable Loro id, never
-- its name), the UTF-16 offsets in it, and the state those offsets are offsets
-- into. That state is named twice, because the two names answer different
-- questions and one of them outlives the other: `source_sequence` is the log
-- row that made it durable, which is what says the comment and the text it
-- quotes were written in one transaction; `frontier` is the Loro frontier,
-- which is what `fork_at` needs and which survives the compaction that deletes
-- the row.
--
-- The rendered words stay, in their own columns, under names that say what they
-- are: what the comment looked like where it was made -- worth showing a
-- person, never resolved through.
CREATE TABLE annotations (
    id uuid PRIMARY KEY,
    document_id uuid NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    kind text NOT NULL CHECK (kind IN ('comment','highlight','suggestion')),
    body text NOT NULL,
    author_account_id uuid REFERENCES accounts(id),
    author_key text NOT NULL,
    author_label text NOT NULL,
    color text,

    -- The log row that made the quoted text durable, and the frontier of the
    -- state the range was measured against.
    source_sequence bigint CHECK (source_sequence IS NULL OR source_sequence >= 0),
    frontier bytea,
    -- The projection digest of the rendered page this remark was made against,
    -- when it was made by a reader rather than in the editor. A comment whose
    -- render is no longer the head projection is refused with the current
    -- digest rather than anchored against text the reader never saw (§7.1).
    render_digest bytea CHECK (render_digest IS NULL OR octet_length(render_digest) = 32),

    target_kind text NOT NULL,
    file_id text,
    start_utf16 integer,
    end_utf16 integer,
    start_side text,
    end_side text,
    exact text,
    prefix text,
    suffix text,

    rendered_exact text NOT NULL DEFAULT '',
    rendered_prefix text NOT NULL DEFAULT '',
    rendered_suffix text NOT NULL DEFAULT '',
    rendered_position_utf16 integer,

    resolved_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT annotations_target_kind CHECK (target_kind IN ('source_text', 'document')),
    -- A passage carries a range and its evidence; a remark about the document
    -- as a whole carries none of it. Neither can be half filled in.
    CONSTRAINT annotations_source_text_target CHECK (
        (target_kind = 'source_text'
            AND file_id IS NOT NULL
            AND start_utf16 IS NOT NULL AND start_utf16 >= 0
            AND end_utf16 IS NOT NULL AND end_utf16 >= start_utf16
            AND start_side IN ('left', 'right')
            AND end_side IN ('left', 'right')
            AND exact IS NOT NULL AND prefix IS NOT NULL AND suffix IS NOT NULL)
        OR
        (target_kind = 'document'
            AND file_id IS NULL
            AND start_utf16 IS NULL AND end_utf16 IS NULL
            AND start_side IS NULL AND end_side IS NULL
            AND exact IS NULL AND prefix IS NULL AND suffix IS NULL)
    )
);
CREATE INDEX annotations_timeline ON annotations(document_id, created_at, id);
-- Finding every comment on a file, which is what a resolution pass walks.
CREATE INDEX annotations_source_file ON annotations(document_id, file_id, created_at, id)
    WHERE file_id IS NOT NULL;

CREATE TABLE replies (
    id uuid PRIMARY KEY,
    annotation_id uuid NOT NULL REFERENCES annotations(id) ON DELETE CASCADE,
    author_account_id uuid REFERENCES accounts(id),
    author_key text NOT NULL,
    author_label text NOT NULL,
    body text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX replies_timeline ON replies(annotation_id, created_at, id);

-- Content-addressed and unique per (document_id, digest, byte_length). Nothing
-- deletes from this table, and the orphan sweeper treats every key it names as
-- live.
CREATE TABLE document_assets (
    id uuid PRIMARY KEY,
    document_id uuid NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    storage_key text NOT NULL UNIQUE,
    digest bytea NOT NULL CHECK (octet_length(digest) = 32),
    byte_length bigint NOT NULL CHECK (byte_length >= 0),
    media_type text NOT NULL,
    original_name text,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (document_id, digest, byte_length)
);

-- A named moment: what somebody asked to be able to come back to.
--
-- Nothing writes one on a timer. A label names a state by three things at
-- once -- the version vector, the Loro frontier and the projection digest --
-- because each answers a different question: the vector says what the log
-- held, the frontier is what `fork_at` reconstructs from, and the digest is
-- what says two labels name the same document.
--
-- Its plain-source archive is produced on request rather than at label time
-- (§8.5). `archive_requested_at` with no `archive_key` is the durable state
-- the startup scan rediscovers; there is no queue row to lose.
CREATE TABLE document_labels (
    id uuid PRIMARY KEY,
    document_id uuid NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    sequence bigint NOT NULL CHECK (sequence >= 1),
    -- The log row that made this state durable.
    source_sequence bigint NOT NULL CHECK (source_sequence >= 0),
    vector bytea NOT NULL,
    frontier bytea NOT NULL,
    tree_digest bytea CHECK (tree_digest IS NULL OR octet_length(tree_digest) = 32),
    label text,
    -- Why it exists: `label` for one somebody named, and the name of the
    -- command for the retry record a source-producing command writes (§7.2):
    -- `restore`, `agent-patch`, `replace`, `accept`.
    reason text NOT NULL,
    -- The client's idempotency key for a source-producing command. A retry
    -- with the same id finds this row and returns its result.
    request_id uuid UNIQUE,
    author_account_id uuid REFERENCES accounts(id),
    author_label text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    archive_requested_at timestamptz,
    archive_key text,
    archive_error text,
    UNIQUE (document_id, sequence)
);
CREATE INDEX document_labels_timeline ON document_labels(document_id, sequence DESC);
-- The startup scan for archives that were asked for and never landed.
CREATE INDEX document_labels_archive_pending
    ON document_labels(document_id, sequence)
    WHERE archive_requested_at IS NOT NULL AND archive_key IS NULL;
-- Storage accounting looks up siblings by key on every write and delete, and
-- the backup enumerator and the orphan sweeper read this column too.
CREATE INDEX document_labels_archive_key ON document_labels(archive_key)
    WHERE archive_key IS NOT NULL;

-- A proposed change is a branch, and its status lives here rather than in the
-- document. A client that can write to the document can write to anything
-- stored in it, including the record that says whether its own edit was
-- approved; keeping the decision here is what makes it server-owned.
--
-- The branch itself is stored here too, as the operations since its fork. A
-- base is large, long-lived and read on cold start; a branch is none of those.
-- More decisively, accepting a proposal has to write the decision and the
-- resulting source together or not at all, and one transaction over one store
-- is how that is actually achieved.
CREATE TABLE document_proposals (
    id uuid PRIMARY KEY,
    document_id uuid NOT NULL REFERENCES documents(id) ON DELETE CASCADE,

    -- Who opened it, for attribution in the UI. The authorship that matters is
    -- not this: it is carried by the operations themselves, and survives a
    -- partial accept because the branch is merged whole.
    author text NOT NULL,

    -- The peer that wrote the branch. Kept so the sequencer can tell a
    -- proposal's own operations from everyone else's without decoding the blob.
    author_peer bigint NOT NULL,

    -- Encoded frontiers. `base` is where the branch forked; `tip` is where it
    -- had reached when it was last updated. Review is the diff between them, and
    -- a decision names the tip it was computed against so that a decision made
    -- against a stale tip can be refused rather than applied to text that has
    -- since changed underneath the reviewer.
    base_frontiers bytea NOT NULL,
    tip_frontiers bytea NOT NULL,

    -- The branch: Loro operations since the fork, not a whole document.
    branch_bytes bytea NOT NULL,

    -- `pending` until every hunk has been decided; then `resolved`. A proposal
    -- that the document has moved past without deciding is `superseded`.
    status text NOT NULL CHECK (status IN ('pending', 'resolved', 'superseded')),

    -- Bumped by every transition, so a conditional update can refuse a
    -- decision made against a row somebody else has already moved (§7.2).
    version bigint NOT NULL DEFAULT 1 CHECK (version >= 1),

    -- Set when the proposal resolves, together in one write with the source
    -- that carried its accepted hunks into the document.
    resolved_by text,
    resolved_at timestamptz,

    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

-- The open proposals for a document, which is what a joining client asks for and
-- what the sequencer broadcasts after every decision.
CREATE INDEX document_proposals_open ON document_proposals(document_id, status);

-- A suggestion annotation is the human-facing discussion attached to one
-- proposal branch. Keep the relation explicit so catalog reloads cannot turn
-- a reviewable suggestion into an ordinary comment.
ALTER TABLE annotations
    ADD COLUMN proposal_id uuid UNIQUE REFERENCES document_proposals(id) ON DELETE CASCADE;
ALTER TABLE annotations
    ADD CONSTRAINT annotations_suggestion_proposal CHECK (
        (kind = 'suggestion' AND proposal_id IS NOT NULL)
        OR (kind <> 'suggestion' AND proposal_id IS NULL)
    );

-- One row per decision, because a reviewer decides hunks and not proposals.
--
-- A hunk is named by its index in the diff of a named tip against a named base.
-- That identity is deliberately free of any offset: the server counts hunks in
-- code points and the browser counts them in UTF-16, so an index is the one way
-- to name a hunk that means the same thing on both sides. It is stable only
-- against the tip it was computed from, which is why that tip is recorded
-- beside it.
CREATE TABLE document_proposal_hunks (
    proposal_id uuid NOT NULL REFERENCES document_proposals(id) ON DELETE CASCADE,
    hunk_index integer NOT NULL CHECK (hunk_index >= 0),
    accepted boolean NOT NULL,
    decided_by text NOT NULL,
    decided_at timestamptz NOT NULL DEFAULT now(),

    -- The tip this decision was computed against. A decision whose tip is no
    -- longer the proposal's tip was made about a diff that no longer exists.
    decided_against bytea NOT NULL,

    -- A reviewer may say why, and declining is where that matters most.
    note text,

    PRIMARY KEY (proposal_id, hunk_index)
);

-- One deployment writer fences every document transaction. The row lock,
-- rather than an unlocked epoch read, remains held until commit.
CREATE TABLE deployment_writer (
    singleton boolean PRIMARY KEY DEFAULT true CHECK (singleton),
    epoch bigint NOT NULL DEFAULT 0 CHECK (epoch >= 0),
    activated_at timestamptz NOT NULL DEFAULT now()
);
INSERT INTO deployment_writer(singleton) VALUES(true) ON CONFLICT DO NOTHING;

-- Durable deployment-scoped payloads. The server owns each value's JSON schema
-- and replaces it atomically. The deployment's own Loro peer id -- the one
-- server-authored source is written under (§7.3) -- lives here.
CREATE TABLE server_runtime_state (
    name text PRIMARY KEY,
    value jsonb NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now()
);

-- Deployment storage counts objects, not references.
--
-- The counter is the number of bytes actually held in the blob store. Archives
-- are named by digest and shared, so a row naming an object some other row
-- already names adds no bytes, and refunding on its delete would decrement the
-- counter for bytes that are still held -- a counter that drifts below the
-- truth eventually admits writes the deployment has no room for.
--
-- So each side asks the same question -- is this row the only one naming this
-- object? -- and moves the counter only then. It is asked in an AFTER trigger,
-- where on INSERT the new row is already visible and must not count itself, and
-- on DELETE the old row is already gone.
CREATE TABLE storage_usage (
    singleton boolean PRIMARY KEY DEFAULT true CHECK (singleton),
    bytes bigint NOT NULL CHECK (bytes >= 0)
);
INSERT INTO storage_usage(bytes) VALUES (0);

-- An asset is unique per (document_id, digest, byte_length) and nothing deletes
-- from that table, so it is always the sole owner of its object.
CREATE FUNCTION adjust_asset_storage_usage() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    UPDATE storage_usage SET bytes = bytes + CASE WHEN TG_OP='INSERT' THEN NEW.byte_length ELSE -OLD.byte_length END;
    IF TG_OP = 'DELETE' THEN RETURN OLD; ELSE RETURN NEW; END IF;
END
$$;

-- A label's archive is named by the digest of the projection it holds, so two
-- labels naming the same document name one object and it is stored once. The
-- key arrives by UPDATE rather than INSERT -- the label exists before its
-- archive does (§8.5) -- so this trigger watches all three verbs and counts a
-- key exactly once across the whole table.
CREATE FUNCTION adjust_label_archive_storage_usage() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    shared boolean;
    weight bigint;
BEGIN
    IF TG_OP <> 'INSERT' AND OLD.archive_key IS NOT NULL
       AND (TG_OP = 'DELETE' OR NEW.archive_key IS DISTINCT FROM OLD.archive_key) THEN
        SELECT EXISTS(SELECT 1 FROM document_labels
                      WHERE archive_key = OLD.archive_key AND id IS DISTINCT FROM OLD.id)
          INTO shared;
        IF NOT shared THEN
            SELECT COALESCE(OLD.archive_bytes, 0) INTO weight;
            UPDATE storage_usage SET bytes = GREATEST(0, bytes - weight);
        END IF;
    END IF;
    IF TG_OP <> 'DELETE' AND NEW.archive_key IS NOT NULL
       AND (TG_OP = 'INSERT' OR NEW.archive_key IS DISTINCT FROM OLD.archive_key) THEN
        SELECT EXISTS(SELECT 1 FROM document_labels
                      WHERE archive_key = NEW.archive_key AND id IS DISTINCT FROM NEW.id)
          INTO shared;
        IF NOT shared THEN
            UPDATE storage_usage SET bytes = bytes + COALESCE(NEW.archive_bytes, 0);
        END IF;
    END IF;
    IF TG_OP = 'DELETE' THEN RETURN OLD; ELSE RETURN NEW; END IF;
END
$$;

-- What the archive weighs, so the trigger above has a number to move. NULL
-- until the archive lands, and set in the same UPDATE as the key.
ALTER TABLE document_labels
    ADD COLUMN archive_bytes bigint CHECK (archive_bytes IS NULL OR archive_bytes >= 0),
    ADD CONSTRAINT document_labels_archive_pair
        CHECK ((archive_key IS NULL) = (archive_bytes IS NULL));

CREATE TRIGGER document_assets_storage_usage AFTER INSERT OR DELETE ON document_assets
    FOR EACH ROW EXECUTE FUNCTION adjust_asset_storage_usage();
CREATE TRIGGER document_labels_storage_usage
    AFTER INSERT OR UPDATE OF archive_key OR DELETE ON document_labels
    FOR EACH ROW EXECUTE FUNCTION adjust_label_archive_storage_usage();
