-- What the project listing says about a project, without opening it.
--
-- The listing shows how many files a project holds and how many comments it
-- has collected. Neither was in the catalogue, so the page fetched
-- `/api/documents/{slug}` once per project to find out -- one request per row,
-- on every load of the landing page, for two numbers. An account with forty
-- projects opened its own home page with forty-one requests.
--
-- The comments were always answerable here: `annotations` is keyed by
-- document and one aggregate covers a whole page of them. The file count was
-- not. A version's files live inside its archive, which is an opaque blob to
-- SQL, so the count has to be written down when the version is written, which
-- is the one moment the file list is in hand.
--
-- Nullable, and deliberately not backfilled. A version committed before this
-- column existed genuinely does not know its file count, and the only way to
-- find out is to fetch and decode its archive -- which is the expensive thing
-- this column exists to avoid, and doing it once per historical version at
-- migration time is worse than doing it never. The listing renders NULL as
-- "--", the same as it renders a project whose count has not arrived yet, and
-- the next commit to any document fills it in for good.
ALTER TABLE document_versions ADD COLUMN file_count integer
    CHECK (file_count IS NULL OR file_count >= 0);
