/* LaTeX adapter for the Insert menu.  Positions in additionalEdits are
 * absolute offsets in the source file named by edit.path. */
const s = (x, d = "") => x == null ? d : String(x);
const n = (x, d, min = 1, max = 100) => Math.min(max, Math.max(min, Number.isFinite(+x) ? Math.floor(+x) : d));
const tex = value => s(value).replace(/[\\{}%#$&_~^]/g, c => ({'\\':'\\textbackslash{}','~':'\\textasciitilde{}','^':'\\textasciicircum{}'}[c] || '\\'+c));
const key = (x) => s(x, "label").trim().replace(/[^\p{L}\p{N}:._-]+/gu, "-").replace(/^-+|-+$/g, "") || "label";
const source = (c = {}) => s(c.mainText || c.text);
const packageEdit = (name, c, notes, options = "") => {
  const text = source(c), path = c.mainPath || c.path;
  if (new RegExp(`\\\\usepackage(?:\\[[^\\]]*\\])?\\{[^}]*\\b${name}\\b[^}]*\\}`).test(text)) return [];
  const classEnd = text.match(/\\documentclass(?:\[[^\]]*\])?\{[^}]+\}[^\S\n]*(?:\n|$)/);
  const at = name === "amsthm" && classEnd ? classEnd.index + classEnd[0].length : text.indexOf("\\begin{document}");
  if (at < 0 || !path) throw new Error(`Cannot add LaTeX dependency \\usepackage${options ? `[${options}]` : ""}{${name}}: main preamble source is unavailable.`);
  return [{ path, from: at, to: at, insert: `\\usepackage${options ? `[${options}]` : ""}{${name}}\n` }];
};
const preambleEdit = (insert, c, notes) => { const text = source(c), path = c.mainPath || c.path, at = text.indexOf("\\begin{document}"); if (at < 0 || !path) throw new Error("Cannot add LaTeX environment setup: main preamble source is unavailable."); return [{ path, from: at, to: at, insert: insert + "\n" }]; };
const result = (text, additionalEdits = [], notes = [], placeholder) => ({ text, additionalEdits, notes, ...(placeholder ? { placeholder } : {}) });
const selected = (c) => s(c.selection?.text, "");
const labelValue = (o, fallback) => o.label ? key(o.label) : fallback;

export function buildLatex(id, options = {}, context = {}) {
  const c = context || {}, text = source(c), body = selected(c), notes = [], additionalEdits = [];
  const title = tex(options.title || body || (id === "appendix" ? "Appendix" : "Heading")), rowCount = n(options.rows, 3), colCount = n(options.columns, 3);
  const add = (pkg, opts) => additionalEdits.push(...packageEdit(pkg, c, notes, opts));
  if (id === "heading") { const level = n(options.level, 1, 1, 5), cmd = ["section", "subsection", "subsubsection", "paragraph", "subparagraph"][level - 1], lab = options.label ? `\\label{${key(options.label)}}` : ""; return result(`\\${cmd}${options.numbered === false ? "*" : ""}{${title}}${lab}`, [], notes, title); }
  if (id === "abstract") return result(`\\begin{abstract}\n${body || "Abstract text."}\n\\end{abstract}`, [], notes, "Abstract text.");
  if (id === "appendix") return result(`\\appendix\n\\section${options.numbered === false ? "*" : ""}{${title}}`, [], notes, title);
  if (id === "toc") return result("\\tableofcontents", [], notes);
  if (id === "figure") { add("graphicx"); if (!options.src) throw Error("Choose an image first."); const src = s(options.src).replace(/[{}%#]/g, c => '\\'+c), rawWidth = options.width, width = /%$/.test(rawWidth || '') ? (parseFloat(rawWidth)/100)+'\\linewidth' : (rawWidth || '\\linewidth'); const caption = tex(options.caption ?? options.title ?? "Figure"); const labelText = labelValue(options, "fig:" + key(options.title || "figure")); return result(`\\begin{figure}[${options.placement || "htbp"}]\n\\centering\n\\includegraphics[width=${width}]{${src}}\n\\caption${options.caption === false ? "*" : ""}{${caption}}${options.caption === false ? "" : `\\label{${labelText}}`}\n\\end{figure}`, additionalEdits, notes); }
  if (id === "table") { const header = options.header !== false, alignment = { left: "l", center: "c", right: "r" }[options.alignment] || (options.alignment === "default" ? "c" : s(options.alignment, "c").slice(0, 1)), align = alignment.repeat(colCount); const cells = []; for (let r = 0; r < rowCount; r++) cells.push(Array.from({ length: colCount }, (_, j) => r === 0 && header ? tex(options.headers?.[j] || `Header ${j + 1}`) : tex(options.cells?.[r]?.[j] || `Cell ${r + 1},${j + 1}`)).join(" & ")); const tabular = `\\begin{tabular}{${align}}\n${header ? "\\toprule\n" : ""}${cells.join(" \\\\\n")}${header ? " \\\\\n\\bottomrule" : ""}\n\\end{tabular}`; if (header) add("booktabs"); const caption = options.caption ? `\\caption{${tex(options.caption)}}\n` : ""; const lab = options.label ? `\\label{${key(options.label)}}\n` : ""; return result(`\\begin{table}[${options.placement || "htbp"}]\n\\centering\n${caption}${lab}${tabular}\n\\end{table}`, additionalEdits, notes); }
  if (id === "citation") { const keys = options.keys || []; if (!keys.length) throw Error("Choose at least one reference."); if (keys.some(k => !/^[\p{L}\p{N}_.:+-]+$/u.test(k))) throw Error("Unsupported citation key."); const loc = options.locator ? `[${tex(options.locator)}]` : ""; const biblatex = /usepackage(?:\[[^]]*\])?\{biblatex\}/.test(text) || c.biblatex; const natbib = /usepackage(?:\[[^]]*\])?\{natbib\}/.test(text); const style = options.style || "parenthetical"; if (!biblatex && !natbib && style === "narrative") additionalEdits.push(...packageEdit("natbib", c, notes)); const command = biblatex ? (style === "narrative" ? "\\textcite" : "\\parencite") : (natbib || style === "narrative") ? (style === "narrative" ? "\\citet" : "\\citep") : "\\cite"; return result(`${command}${loc}{${keys.join(",")}}`, additionalEdits, notes); }
  if (id === "bibliography") { const file = tex(options.file || "references"), bibfile = file.endsWith(".bib") ? file : file + ".bib", hasBiblatex = /usepackage(?:\[[^]]*\])?\{biblatex\}/.test(text) || c.biblatex; if (options.biblatex || hasBiblatex) { if (!/usepackage(?:\[[^]]*\])?\{biblatex\}/.test(text)) additionalEdits.push(...preambleEdit(`\\usepackage[backend=biber]{biblatex}`, c, notes)); if (!new RegExp(`\\\\addbibresource\{${file.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\}`).test(text)) additionalEdits.push(...preambleEdit(`\\addbibresource{${bibfile}}`, c, notes)); return result("\\printbibliography", additionalEdits, notes); } return result(`\\bibliographystyle{${tex(options.style || "plain")}}\n\\bibliography{${file.replace(/\.bib$/, "")}}`, [], notes); }
  if (id === "cross-reference") return result(`\\ref{${key(options.target || "label")}}`, [], notes, options.target || "label");
  if (id === "label") return result(`\\label{${labelValue(options, "label")}}`, [], notes, labelValue(options, "label"));
  if (id === "inline-math") return result(`$${body || "x = y"}$`, [], notes, "x = y");
  if (["display-math", "aligned-math", "gather-math", "cases", "matrix"].includes(id)) { add("amsmath"); const formula = body || "x = y", labelText = options.label ? `\\label{${key(options.label)}}\n` : "", wrap = (inner) => options.inMath ? inner : `\\begin{equation${options.numbered === false ? "*" : ""}}\n${labelText}${inner}\n\\end{equation${options.numbered === false ? "*" : ""}}`; if (id === "cases") { const r = n(options.rows, 2); return result(wrap(`f(x) = \\begin{cases}\n${Array.from({ length: r }, (_, i) => `${tex(options.values?.[i] || "x")} & ${tex(options.conditions?.[i] || `condition ${i + 1}`)}`).join(" \\\\\n")}\n\\end{cases}`), additionalEdits, notes); } if (id === "matrix") { const r = n(options.rows, 2), cols = n(options.columns, 2), env = ({parentheses:"pmatrix",brackets:"bmatrix",braces:"Bmatrix",bars:"vmatrix",doublebars:"Vmatrix",none:"matrix"})[options.brackets] || (["pmatrix","bmatrix","Bmatrix","vmatrix","Vmatrix"].includes(options.brackets) ? options.brackets : "pmatrix"); return result(wrap(`\\begin{${env}}\n${Array.from({ length: r }, () => Array.from({ length: cols }, () => "x").join(" & ")).join(" \\\\\n")}\n\\end{${env}}`), additionalEdits, notes); } const env = id === "aligned-math" ? "align" : id === "gather-math" ? "gather" : "equation"; if (options.inMath) return result(`\\begin{${env === "equation" ? "aligned" : env}}\n${formula}\n\\end{${env === "equation" ? "aligned" : env}}`, additionalEdits, notes, formula); return result(`\\begin{${env}${options.numbered === false ? "*" : ""}}\n${labelText}${formula}\n\\end{${env}${options.numbered === false ? "*" : ""}}`, additionalEdits, notes, formula); }
  if (["bulleted-list", "numbered-list", "description-list"].includes(id)) { const items = (body ? body.split(/\r?\n/).filter(Boolean) : ["First item", "Second item"]); const env = id === "bulleted-list" ? "itemize" : id === "numbered-list" ? "enumerate" : "description"; const content = id === "description-list" ? items.map((x, i) => `\\item[${tex(options.terms?.[i] || `Term ${i + 1}`)}] ${x}`).join("\n") : items.map((x) => `\\item ${x}`).join("\n"); return result(`\\begin{${env}}\n${content}\n\\end{${env}}`, [], notes, "First item"); }
  if (["quote", "quotation"].includes(id)) return result(`\\begin{${id}}\n${body || "Quote"}\n\\end{${id}}`, [], notes, "Quote");
  if (id === "code-block") { const language = s(options.language).toLowerCase(), known = { python: "Python", r: "R", javascript: "JavaScript", js: "JavaScript", bash: "bash", sh: "bash", rust: "Rust" }; if (!language) return result(`\\begin{verbatim}\n${body || "code"}\n\\end{verbatim}`, [], notes, "code"); if (!known[language]) throw new Error(`Unsupported listings language: ${language}`); add("listings"); return result(`\\begin{lstlisting}[language=${known[language]}]\n${body || "code"}\n\\end{lstlisting}`, additionalEdits, notes, "code"); }
  if (id === "footnote") return result(`\\footnote{${body || "Note"}}`, [], notes, "Note");
  if (id === "link") { add("hyperref"); return result(`\\href{${s(options.url || "https://example.com").replace(/[{}%#&]/g, c => "\\"+c)}}{${body || tex(options.title || "Link")}}`, additionalEdits, notes, "Link"); }
  if (["theorem", "lemma", "proposition", "definition", "proof", "example", "remark"].includes(id)) { add("amsthm"); const declared = new RegExp(`\\\\newtheorem(?:\[[^]]*\])?\\{${id.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\}`).test(text); if (!declared && id !== "proof") additionalEdits.push(...preambleEdit(`\\newtheorem{${id}}{${id[0].toUpperCase() + id.slice(1)}}`, c, notes)); const lab = options.label ? `\\label{${key(options.label)}}\n` : ""; return result(`\\begin{${id}}${options.title ? `[${tex(options.title)}]` : ""}\n${lab}${body || "Statement."}\n\\end{${id}}`, additionalEdits, notes, "Statement."); }
  if (id === "page-break") return result(options.strong ? "\\clearpage" : "\\newpage", [], notes);
  if (id === "horizontal-rule") return result("\\noindent\\rule{\\linewidth}{0.4pt}", [], notes);
  if (id === "columns") { add("multicol"); const gap = options.gap ? `\n\\setlength{\\columnsep}{${s(options.gap)}}` : ""; return result(`${gap}\\begin{multicols}{${n(options.columns, 2)}}\n${body || "Column content."}\n\\end{multicols}`, additionalEdits, notes, "Column content."); }
  if (id === "custom-environment") { const env = key(options.environment || "environment"); if (!new RegExp(`\\\\newenvironment\\{${env}\\}`).test(text) && !new RegExp(`\\\\newtheorem\\{${env}\\}`).test(text)) throw new Error(`LaTeX environment '${env}' is not defined in the document.`); return result(`\\begin{${env}}\n${body || "Content."}\n\\end{${env}}`, [], notes, "Content."); }
  return result("", [], [`Unknown LaTeX insertion: ${id}`]);
}
