// Bibliography detection and cache identity, over real files and real
// diagnostics.
//
// SPEC "Local Biber operation" step 3 and section 2.8 step 3-4 both say the
// same thing two ways: do not guess what a document needs from a source
// regex, because a commented-out `\usepackage{biblatex}` or a preamble macro
// that expands into one would lie. Ask the engine what it actually wrote --
// the `.bcf`, the `.aux` files, the log -- and ask the tree what is actually
// there. This module is that asking, and nothing else: it never runs an
// engine, never touches a worker, and is exercised in `latex-bibliography.mjs`
// with a handful of hand-written aux/bcf/log strings.

const encoder = new TextEncoder();

async function sha256Hex(bytes) {
  const hash = await crypto.subtle.digest("SHA-256", bytes);
  return [...new Uint8Array(hash)].map((b) => b.toString(16).padStart(2, "0")).join("");
}

function bytesOf(value) {
  if (value == null) return new Uint8Array(0);
  if (value instanceof Uint8Array) return value;
  if (value instanceof ArrayBuffer) return new Uint8Array(value);
  if (ArrayBuffer.isView(value)) return new Uint8Array(value.buffer, value.byteOffset, value.byteLength);
  return encoder.encode(String(value));
}

function textOf(value) {
  if (value == null) return "";
  if (typeof value === "string") return value;
  return new TextDecoder().decode(bytesOf(value));
}

function dirname(path) {
  const at = String(path || "").lastIndexOf("/");
  return at === -1 ? "" : path.slice(0, at);
}

function join(dir, name) {
  return dir ? `${dir}/${name}` : name;
}

/// Resolves a bibliography-adjacent name (a `.bib`, a `.bst`, a biber config)
/// the way TeX itself would from the main file: relative to the main file's
/// own directory first, then the project root. Returns the tree-relative
/// path that actually exists, or `null` when neither does -- a name real
/// files and diagnostics named but the tree does not have is not silently
/// invented into an identity input.
function resolve(name, tree, mainDir) {
  const exists = (path) =>
    Boolean(tree?.texts && Object.prototype.hasOwnProperty.call(tree.texts, path)) ||
    Boolean(tree?.assets && Object.prototype.hasOwnProperty.call(tree.assets, path));
  const candidates = [join(mainDir, name), name];
  for (const candidate of candidates) {
    if (exists(candidate)) return candidate;
  }
  return null;
}

function withExtension(name, ext) {
  return /\.[a-zA-Z0-9]+$/.test(name) ? name : `${name}${ext}`;
}

/// `\bibdata{a,b,c}` -> classic BibTeX's own record of the databases it was
/// given, comma-separated and conventionally extension-less.
function bibdataNames(auxText) {
  const names = [];
  const re = /\\bibdata\{([^}]*)\}/g;
  let match;
  while ((match = re.exec(auxText))) {
    for (const raw of match[1].split(",")) {
      const trimmed = raw.trim();
      if (trimmed) names.push(withExtension(trimmed, ".bib"));
    }
  }
  return names;
}

/// `\bibstyle{name}` -> the `.bst` classic BibTeX was told to use.
function bibstyleNames(auxText) {
  const names = [];
  const re = /\\bibstyle\{([^}]*)\}/g;
  let match;
  while ((match = re.exec(auxText))) {
    const trimmed = match[1].trim();
    if (trimmed) names.push(withExtension(trimmed, ".bst"));
  }
  return names;
}

/// `<bcf:datasource type="file" ...>name.bib</bcf:datasource>` -> Biber's own
/// record of the databases, already carrying their extension. A minimal
/// regex is enough: the bcf is machine-generated by biblatex, not authored,
/// so it is well-formed and this module never needs a real XML parser for it.
function bcfDatasources(bcfText) {
  const names = [];
  const re = /<bcf:datasource\b[^>]*>([^<]+)<\/bcf:datasource>/g;
  let match;
  while ((match = re.exec(bcfText))) {
    const trimmed = match[1].trim();
    if (trimmed) names.push(trimmed);
  }
  return names;
}

/// `\@input{path.aux}` -> a nested auxiliary file TeX included, followed
/// recursively so a multi-file document's bibliography commands are found
/// wherever `\include`d chapters put them.
function inputAuxPaths(auxText) {
  const paths = [];
  const re = /\\@input\{([^}]*)\}/g;
  let match;
  while ((match = re.exec(auxText))) {
    const trimmed = match[1].trim();
    if (trimmed) paths.push(trimmed);
  }
  return paths;
}

/// Whether the log is asking for Biber, in Biber's own words -- `biblatex`
/// prints exactly this line into the log when the bcf needs (re)processing.
function logAsksForBiber(log) {
  return /Please \(re\)run Biber/i.test(log || "");
}

/// Whether the log says citations are undefined, which is the shared signal
/// classic BibTeX and Biber both need before their first run (there is no
/// `.bbl` yet, so nothing else would say so).
function logUndefinedCitations(log) {
  return /LaTeX Warning: Citation .* undefined/i.test(log || "") || /No file .*\.bbl\./i.test(log || "");
}

/// Inspects one job's real outputs and log for the bibliography and index
/// work SPEC section 2.8 step 3 describes. `stem` is the job name (e.g.
/// `"main"`); `outputs` is the `tex` reply's `outputs` map (path -> bytes);
/// `log` is that pass's TeX log; `tree` is the project, used only to decide
/// whether a name the aux/bcf mentioned is actually present.
export function inspect({ stem, outputs = {}, log = "", tree = {} }) {
  const mainDir = dirname(tree?.main);
  const auxPaths = [];
  const seen = new Set();
  const queue = [`${stem}.aux`];
  let auxText = "";
  const bibNames = new Set();
  const bstNames = new Set();

  while (queue.length) {
    const path = queue.shift();
    if (seen.has(path)) continue;
    seen.add(path);
    const bytes = outputs[path];
    if (bytes == null) continue;
    auxPaths.push(path);
    const text = textOf(bytes);
    if (path === `${stem}.aux`) auxText = text;
    for (const name of bibdataNames(text)) bibNames.add(name);
    for (const name of bibstyleNames(text)) bstNames.add(name);
    for (const nested of inputAuxPaths(text)) queue.push(nested);
  }

  const bcfPath = `${stem}.bcf`;
  const bcf = outputs[bcfPath] instanceof Uint8Array ? outputs[bcfPath] : outputs[bcfPath] ? bytesOf(outputs[bcfPath]) : null;
  if (bcf) {
    for (const name of bcfDatasources(textOf(bcf))) bibNames.add(name);
  }

  const biber = Boolean(bcf) && logAsksForBiber(log);
  const hasBibdata = bibNames.size > 0;
  const bblPath = `${stem}.bbl`;
  const needsFirstRun = !outputs[bblPath] || logUndefinedCitations(log);
  // Classic BibTeX only applies when the aux actually asked for a
  // bibliography (`\bibdata`) and there is no bcf -- a bcf means biblatex,
  // and biblatex is never silently downgraded to BibTeX (SPEC "BibTeX is
  // never a silent replacement for Biber").
  const bibtexNeeded = !bcf && hasBibdata && needsFirstRun;
  const bibtex8 = bibtexNeeded && (/backend\s*=\s*bibtex8/i.test(auxText) || /bibtex8/i.test(log));
  const bibtex = bibtexNeeded && !bibtex8;

  const idxPath = `${stem}.idx`;
  const makeindex = Boolean(outputs[idxPath]);

  const configFiles = [];
  const styleFiles = [];
  const bibFiles = [];
  const allTreePaths = new Set([...Object.keys(tree?.texts || {}), ...Object.keys(tree?.assets || {})]);
  for (const path of allTreePaths) {
    const base = path.slice(path.lastIndexOf("/") + 1);
    if (base === "biber.conf" || base === ".bibrc" || /\.(bbx|cbx|lbx)$/i.test(base)) configFiles.push(path);
  }
  for (const name of bibNames) {
    const found = resolve(name, tree, mainDir);
    bibFiles.push(found || name);
  }
  for (const name of bstNames) {
    const found = resolve(name, tree, mainDir);
    if (found) styleFiles.push(found);
  }

  return {
    biber,
    bibtex,
    bibtex8,
    makeindex,
    auxPaths,
    bcf,
    bibFiles: [...new Set(bibFiles)].sort(),
    styleFiles: [...new Set(styleFiles)].sort(),
    configFiles: [...new Set(configFiles)].sort(),
  };
}

/// The bibliography input identity SPEC section 2.8 step 4 asks for: a sha256
/// over the control bytes (the bcf for Biber, the aux for BibTeX) plus every
/// `.bib`/`.bst`/config file's own path and bytes plus the engine, release
/// and tool identity. Sorted by path so the hash is independent of iteration
/// order; a citation, a `.bib` byte, a `.bst`, a biblatex option (carried in
/// the bcf) or a tool/engine/release change all change `controlBytes` or
/// `files` and therefore this hash, while a prose-only edit -- which touches
/// none of those -- reuses it exactly.
export async function identity({ kind, controlBytes, files = {}, engine, release, tool }) {
  const entries = Object.entries(files)
    .map(([path, bytes]) => [path, bytesOf(bytes)])
    .sort((a, b) => (a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0));

  const toolTag =
    tool == null ? "" : typeof tool === "string" ? tool : `${tool.name || ""}:${tool.version || ""}:${tool.backend || ""}`;

  const parts = [
    encoder.encode(`kind:${kind || ""}\nengine:${engine || ""}\nrelease:${release || ""}\ntool:${toolTag}\n`),
  ];
  const control = bytesOf(controlBytes);
  parts.push(encoder.encode(`control:${control.length}\n`));
  parts.push(control);
  for (const [path, bytes] of entries) {
    parts.push(encoder.encode(`\nfile:${path}:${bytes.length}\n`));
    parts.push(bytes);
  }

  let total = 0;
  for (const part of parts) total += part.length;
  const buffer = new Uint8Array(total);
  let offset = 0;
  for (const part of parts) {
    buffer.set(part, offset);
    offset += part.length;
  }
  return sha256Hex(buffer);
}
