//! The test suite, in the shape the Go one had: a server in this process, a
//! client that speaks to it the way the shell and the command line do, and
//! one file per concern.

mod harness;
pub use harness::*;

mod admission;
mod agent_transactions;
mod assets;
mod assistant;
mod assistant_protocol;
mod auth;
mod auth_regressions;
mod automation;
mod blob;
mod catalogue_room;
mod checkpoint_attribution;
mod commands;
mod device;
mod directories;
pub mod edit;
mod export;
mod figures;
mod guests;
mod hardening;
mod history;
mod latex;
mod local;
mod mcp;
mod mirror_server;
mod onboarding;
mod ownership;
mod persistence_capacity;
mod persistence_defaults;
mod pseudonym;
mod publication_delivery;
mod publication_quotas;
mod publication_security;
mod publish_cli;
mod quarto_local;
mod quarto_source;
mod quota;
mod quota_preferences;
mod renderings;
mod retention;
mod room;
mod room_checkpoint_fixes;
mod room_figure_fixes;
mod room_lifecycle_fixes;
mod room_lock_scopes;
mod room_suggestion_fixes;
mod seed;
mod serve;
mod session;
mod sharing;
mod size_limits;
mod sockets;
mod source_anchor;
mod store;
mod suggestions;
mod sync;
mod timeline;
mod tokens;
mod typst_needs;
mod uploads;
mod visitor;
mod write_errors;
pub mod yjs;
