#!/usr/bin/env bash
set -euo pipefail

: "${SCOOP_BUCKET_GITHUB_TOKEN:?SCOOP_BUCKET_GITHUB_TOKEN is required}"
source "$(dirname "${BASH_SOURCE[0]}")/release-updater-common.sh"

tag="$(release_updater_validate_tag "${LIBREPAPER_RELEASE_TAG:-${GITHUB_REF_NAME:-}}")"

version="${tag#v}"
archive="librepaper-x86_64-pc-windows-msvc.zip"
release_url="https://github.com/LibrePaper/librepaper/releases/download/${tag}"
tmpdir="$(mktemp -d)"
trap 'rm -rf "${tmpdir}"' EXIT

actual="$(release_updater_fetch_verified_asset "${tag}" "${archive}" "${tmpdir}")"

release_updater_configure_github_auth "${SCOOP_BUCKET_GITHUB_TOKEN}"
bucket_dir="${tmpdir}/scoop-bucket"
git clone https://github.com/vincentarelbundock/scoop-bucket.git "${bucket_dir}"
cd "${bucket_dir}"

mkdir -p bucket
cat > bucket/librepaper.json <<MANIFEST
{
    "##": "This file is generated by LibrePaper's release workflow. DO NOT EDIT.",
    "version": "${version}",
    "description": "Browser based document collaboration and review companion",
    "homepage": "https://github.com/LibrePaper/librepaper",
    "license": "MIT",
    "architecture": {
        "64bit": {
            "url": "${release_url}/${archive}",
            "hash": "${actual}"
        }
    },
    "bin": "librepaper.exe",
    "checkver": {
        "github": "https://github.com/LibrePaper/librepaper"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/LibrePaper/librepaper/releases/download/v\$version/${archive}"
            }
        },
        "hash": {
            "url": "\$url.sha256"
        }
    },
    "notes": [
        "LibrePaper's Windows companion is installed as librepaper.exe. Start it with: librepaper",
        "Upgrade with: scoop update librepaper"
    ]
}
MANIFEST

release_updater_publish_file bucket/librepaper.json \
  "Scoop manifest already up to date" "Update librepaper manifest to ${tag}" main
