#!/usr/bin/env bash
set -euo pipefail

: "${HOMEBREW_TAP_GITHUB_TOKEN:?HOMEBREW_TAP_GITHUB_TOKEN is required}"
source "$(dirname "${BASH_SOURCE[0]}")/release-updater-common.sh"

tag="$(release_updater_validate_tag "${LIBREPAPER_RELEASE_TAG:-${GITHUB_REF_NAME:-}}")"

version="${tag#v}"
release_url="https://github.com/LibrePaper/librepaper/releases/download/${tag}"
tmpdir="$(mktemp -d)"
trap 'rm -rf "${tmpdir}"' EXIT

linux_x86="$(release_updater_fetch_verified_asset "${tag}" librepaper-x86_64-unknown-linux-musl.tar.xz "${tmpdir}")"
linux_arm="$(release_updater_fetch_verified_asset "${tag}" librepaper-aarch64-unknown-linux-musl.tar.xz "${tmpdir}")"
mac_x86="$(release_updater_fetch_verified_asset "${tag}" librepaper-x86_64-apple-darwin.tar.xz "${tmpdir}")"
mac_arm="$(release_updater_fetch_verified_asset "${tag}" librepaper-aarch64-apple-darwin.tar.xz "${tmpdir}")"

# Put the token in Git's environment config rather than a URL or command line,
# so it cannot appear in clone output or process arguments.
release_updater_configure_github_auth "${HOMEBREW_TAP_GITHUB_TOKEN}"
tap_dir="${tmpdir}/homebrew-tap"
git clone https://github.com/vincentarelbundock/homebrew-tap.git "${tap_dir}"
cd "${tap_dir}"

mkdir -p Formula
cat > Formula/librepaper.rb <<FORMULA
# typed: false
# frozen_string_literal: true

# This file is generated by LibrePaper's release workflow. DO NOT EDIT.
class Librepaper < Formula
  desc "Browser based document collaboration and review companion"
  homepage "https://github.com/LibrePaper/librepaper"
  version "${version}"
  license "MIT"

  on_macos do
    on_arm do
      url "${release_url}/librepaper-aarch64-apple-darwin.tar.xz"
      sha256 "${mac_arm}"
    end
    on_intel do
      url "${release_url}/librepaper-x86_64-apple-darwin.tar.xz"
      sha256 "${mac_x86}"
    end
  end

  on_linux do
    on_arm do
      url "${release_url}/librepaper-aarch64-unknown-linux-musl.tar.xz"
      sha256 "${linux_arm}"
    end
    on_intel do
      url "${release_url}/librepaper-x86_64-unknown-linux-musl.tar.xz"
      sha256 "${linux_x86}"
    end
  end

  def install
    bin.install "librepaper"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/librepaper --version")
  end
end
FORMULA

release_updater_publish_file Formula/librepaper.rb \
  "Homebrew formula already up to date" "Update librepaper formula to ${tag}" main
