//! Annotation and reply persistence for the v2 catalogue.

use super::*;

fn annotation_session_active(tx: &rusqlite::Transaction<'_>, authority: AnnotationAuthority<'_>) -> CatalogResult<()> {
    if authority.account_id.is_empty() { return Ok(()); }
    let active: bool = tx.query_row(
        "SELECT EXISTS(SELECT 1 FROM accounts WHERE id=?1 AND status='active' AND session_generation=?2)",
        params![authority.account_id, authority.generation], |row| row.get(0),
    ).map_err(CatalogError::from)?;
    if active { Ok(()) } else { Err(CatalogError::Conflict("comment session generation changed".into())) }
}

fn millis(value: &str) -> i64 {
    value.parse::<i64>().ok().map(|value| if value < 10_000_000_000 { value.saturating_mul(1_000) } else { value })
        .or_else(|| crate::util::parse_timestamp(value).map(|value| value.saturating_mul(1_000)))
        .unwrap_or(0)
}
fn timestamp(value: i64) -> String { crate::util::format_unix(value.saturating_div(1_000)) }
fn document_id(tx: &rusqlite::Transaction<'_>, slug: &str) -> CatalogResult<String> { tx.query_row("SELECT id FROM documents WHERE slug=?1 AND status='active'", [slug], |row| row.get(0)).optional().map_err(CatalogError::from)?.ok_or(CatalogError::NotFound) }
fn document_id_connection(connection: &rusqlite::Connection, slug: &str) -> CatalogResult<String> { connection.query_row("SELECT id FROM documents WHERE slug=?1 AND status='active'", [slug], |row| row.get(0)).optional().map_err(CatalogError::from)?.ok_or(CatalogError::NotFound) }
fn selector(comment: &Comment) -> String { serde_json::json!({"version":1,"rendered":{"exact":comment.exact,"prefix":comment.prefix,"suffix":comment.suffix,"position":comment.position,"region":comment.region,"point":comment.point,"color":comment.color,"quartoOutput":comment.quarto_output},"source":{"path":comment.source_path,"exact":comment.source_exact,"prefix":comment.source_prefix,"suffix":comment.source_suffix,"position":comment.source_position}}).to_string() }
fn context(comment: &Comment) -> String { serde_json::json!({"version":1,"pass":comment.pass,"publicationId":comment.publication_id}).to_string() }

const COMMENT_SELECT: &str = "SELECT d.slug,a.id,a.seq,a.kind,a.body,a.author_key,a.author_label,a.via,CAST(a.created_at AS TEXT),COALESCE(a.publication_id,''),COALESCE(json_extract(a.selector_json,'$.rendered.exact'),''),COALESCE(json_extract(a.selector_json,'$.rendered.prefix'),''),COALESCE(json_extract(a.selector_json,'$.rendered.suffix'),''),json_extract(a.selector_json,'$.rendered.position'),json_extract(a.selector_json,'$.rendered.region'),json_extract(a.selector_json,'$.rendered.quartoOutput'),json_extract(a.selector_json,'$.source.path'),json_extract(a.selector_json,'$.source.exact'),json_extract(a.selector_json,'$.source.prefix'),json_extract(a.selector_json,'$.source.suffix'),json_extract(a.selector_json,'$.source.position'),a.proposed_text,COALESCE(a.suggestion_state,''),COALESCE(a.acceptance_operation_id,''),COALESCE(a.resolution_revision,''),COALESCE(json_extract(a.context_json,'$.pass'),''),a.resolved_at IS NOT NULL,CAST(a.resolved_at AS TEXT),COALESCE(a.resolution_revision,''),COALESCE(json_extract(a.selector_json,'$.rendered.point'),0),json_extract(a.selector_json,'$.rendered.color') FROM annotations a JOIN documents d ON d.id=a.document_id";

impl Catalog {
    pub fn insert_comment(&self, comment: &Comment) -> CatalogResult<Comment> { self.insert_comment_authorized(comment, AnnotationAuthority::default()) }
    fn insert_comment_authorized(&self, comment: &Comment, authority: AnnotationAuthority<'_>) -> CatalogResult<Comment> {
        if comment.slug.is_empty() || comment.id.is_empty() || comment.body.len() > 65_536 { return Err(CatalogError::Invalid("invalid comment".into())); }
        self.immediate(|tx| {
            annotation_session_active(tx, authority)?; let doc=document_id(tx,&comment.slug)?;
            let count:i64=tx.query_row("SELECT count(*) FROM annotations WHERE document_id=?1",[&doc],|r|r.get(0)).map_err(CatalogError::from)?; if count>=500{return Err(CatalogError::Conflict("comment limit reached".into()));}
            let seq:i64=tx.query_row("SELECT next_annotation_seq FROM documents WHERE id=?1",[&doc],|r|r.get(0)).map_err(CatalogError::from)?;
            let kind=if comment.motivation=="editing"{"suggestion"}else if comment.motivation=="highlight"{"highlight"}else{"comment"};
            let (proposed,state)=if kind=="suggestion"{(Some(comment.proposed.as_deref().unwrap_or(&comment.body)),Some(if comment.outcome.is_empty(){"proposed"}else{comment.outcome.as_str()}))}else{(None,None)};
            let created=millis(&comment.created); let resolved_at=comment.resolved_at.as_deref().map(millis);
            tx.execute("INSERT INTO annotations(document_id,id,seq,kind,body,author_account_id,author_key,author_label,via,created_at,updated_at,publication_id,source_revision,selector_json,context_json,proposed_text,suggestion_state,acceptance_operation_id,resolution_revision,resolved_at) VALUES(?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?10,?11,?12,?13,?14,?15,?16,?17,?18,?19)",params![doc,comment.id,seq,kind,comment.body,(!authority.account_id.is_empty()).then_some(authority.account_id),comment.creator,comment.author,comment.via,created,(!comment.publication_id.is_empty()).then_some(comment.publication_id.as_str()),(!comment.pass.is_empty()).then_some(comment.pass.as_str()),selector(comment),context(comment),proposed,state,(!comment.accept_request.is_empty()).then_some(comment.accept_request.as_str()),(!comment.revision.is_empty()).then_some(comment.revision.as_str()),resolved_at]).map_err(CatalogError::from)?;
            tx.execute("UPDATE documents SET next_annotation_seq=next_annotation_seq+1,updated_at=max(updated_at,?1) WHERE id=?2",params![created,doc]).map_err(CatalogError::from)?; Self::comment_in_tx(tx,&comment.slug,&comment.id)
        })
    }
    pub fn insert_comment_request(&self, comment:&Comment, _request_id:&str, _request_digest:&str, _created_at:i64)->CatalogResult<Comment>{self.insert_comment(comment)}
    pub fn insert_comment_request_authorized(&self, comment:&Comment, _request_id:&str, _request_digest:&str, _created_at:i64, authority:AnnotationAuthority<'_>)->CatalogResult<Comment>{self.insert_comment_authorized(comment,authority)}
    pub fn comments(&self,slug:&str,after_seq:Option<i64>,limit:u32)->CatalogResult<Vec<Comment>>{let limit=i64::from(limit.clamp(1,500));self.with_connection(|c|{let mut s=c.prepare(&format!("{COMMENT_SELECT} WHERE d.slug=?1 AND (?2 IS NULL OR a.seq>?2) ORDER BY a.seq LIMIT ?3")).map_err(CatalogError::from)?;let mut rows=s.query(params![slug,after_seq,limit]).map_err(CatalogError::from)?;let mut out=Vec::new();while let Some(r)=rows.next().map_err(CatalogError::from)?{out.push(Self::read_comment(r).map_err(CatalogError::from)?);}Ok(out)})}
    pub fn comment(&self,slug:&str,id:&str)->CatalogResult<Comment>{self.with_connection(|c|{let mut s=c.prepare(&format!("{COMMENT_SELECT} WHERE d.slug=?1 AND a.id=?2")).map_err(CatalogError::from)?;s.query_row(params![slug,id],Self::read_comment).map_err(CatalogError::from)})}
    pub fn resolve_comment(&self,slug:&str,id:&str,resolved:bool,at:Option<&str>,in_checkpoint:&str)->CatalogResult<Comment>{self.immediate(|tx|{let doc=document_id(tx,slug)?;let changed=if resolved{tx.execute("UPDATE annotations SET resolved_at=?3,resolution_revision=?4,updated_at=?3 WHERE document_id=?1 AND id=?2",params![doc,id,at.map(millis).unwrap_or_else(unix_millis),in_checkpoint]).map_err(CatalogError::from)?}else{tx.execute("UPDATE annotations SET resolved_at=NULL,resolution_revision=NULL,updated_at=max(updated_at,?3) WHERE document_id=?1 AND id=?2",params![doc,id,unix_millis()]).map_err(CatalogError::from)?};if changed!=1{return Err(CatalogError::NotFound)}Self::comment_in_tx(tx,slug,id)})}
    pub fn update_comment(&self,comment:&Comment)->CatalogResult<Comment>{self.update_comment_authorized(comment,AnnotationAuthority::default())}
    pub fn update_comment_authorized(&self,comment:&Comment,authority:AnnotationAuthority<'_>)->CatalogResult<Comment>{self.immediate(|tx|{annotation_session_active(tx,authority)?;let doc=document_id(tx,&comment.slug)?;let updated=millis(&comment.created);let changed=tx.execute("UPDATE annotations SET body=?3,author_key=?4,author_label=?5,via=?6,updated_at=max(updated_at,?7),publication_id=?8,source_revision=?9,selector_json=?10,context_json=?11,proposed_text=?12,suggestion_state=?13,resolution_revision=?14,resolved_at=?15 WHERE document_id=?1 AND id=?2 AND seq=?16",params![doc,comment.id,comment.body,comment.creator,comment.author,comment.via,updated,(!comment.publication_id.is_empty()).then_some(comment.publication_id.as_str()),(!comment.pass.is_empty()).then_some(comment.pass.as_str()),selector(comment),context(comment),comment.proposed,(!comment.outcome.is_empty()).then_some(comment.outcome.as_str()),(!comment.revision.is_empty()).then_some(comment.revision.as_str()),comment.resolved_at.as_deref().map(millis),comment.seq]).map_err(CatalogError::from)?;if changed!=1{return Err(CatalogError::NotFound)}Self::comment_in_tx(tx,&comment.slug,&comment.id)})}

    // Suggestion receipts use the v2 operations table.  The actor key binds a
    // receipt to its annotation and prevents another annotation reusing it.
    pub fn begin_suggestion_accept(&self,slug:&str,comment_id:&str,request_id:&str,request_digest:&str,created_at:i64)->CatalogResult<Option<Comment>>{self.begin_suggestion_accept_authorized(slug,comment_id,request_id,request_digest,created_at,AnnotationAuthority::default())}
    pub fn begin_suggestion_accept_authorized(&self,slug:&str,comment_id:&str,request_id:&str,request_digest:&str,created_at:i64,authority:AnnotationAuthority<'_>)->CatalogResult<Option<Comment>>{if request_id.is_empty()||request_digest.len()!=64{return Err(CatalogError::Invalid("invalid suggestion acceptance receipt".into()))}self.immediate(|tx|{annotation_session_active(tx,authority)?;let doc=document_id(tx,slug)?;let actor=format!("annotation:{comment_id}");let existing:Option<(String,String,String)>=tx.query_row("SELECT id,state,request_digest FROM operations WHERE document_id=?1 AND actor_key=?2 AND request_key=?3",params![doc,actor,request_id],|r|Ok((r.get(0)?,r.get(1)?,r.get(2)?))).optional().map_err(CatalogError::from)?;if let Some((_,state,digest))=existing{if digest!=request_digest{return Err(CatalogError::Conflict("request id was reused with different content".into()))}return if state=="committed"{Self::comment_in_tx(tx,slug,comment_id).map(Some)}else{Ok(None)}}let op=hex::encode(crate::auth::random_bytes(16));let generation:String=tx.query_row("SELECT writer_generation FROM server_state WHERE id=1",[],|r|r.get(0)).map_err(CatalogError::from)?;let now=created_at.max(0);let expiry=now.saturating_add(7*24*60*60*1000);let plan=serde_json::json!({"version":1,"commentId":comment_id}).to_string();tx.execute("INSERT INTO operations(id,document_id,actor_key,request_key,kind,request_digest,state,writer_generation,plan_json,created_at,updated_at,work_expires_at) VALUES(?1,?2,?3,?4,'agent_annotations',?5,'prepared',?6,?7,?8,?8,?9)",params![op,doc,actor,request_id,request_digest,generation,plan,now,expiry]).map_err(CatalogError::from)?;Ok(None)})}
    pub fn record_suggestion_accept_checkpoint(&self,slug:&str,comment_id:&str,request_id:&str,request_digest:&str,resolved_in:&str,resolved_at:&str)->CatalogResult<()>{self.immediate(|tx|{let doc=document_id(tx,slug)?;let result=serde_json::json!({"version":1,"commentId":comment_id,"resolvedIn":resolved_in,"resolvedAt":resolved_at}).to_string();let n=tx.execute("UPDATE operations SET result_json=?1,updated_at=max(updated_at,?2) WHERE document_id=?3 AND actor_key=?4 AND request_key=?5 AND request_digest=?6 AND state='prepared'",params![result,unix_millis(),doc,format!("annotation:{comment_id}"),request_id,request_digest]).map_err(CatalogError::from)?;if n==1{Ok(())}else{Err(CatalogError::Conflict("suggestion acceptance receipt is no longer prepared".into()))}})}
    pub fn stage_suggestion_accept_update(&self,slug:&str,comment_id:&str,request_id:&str,request_digest:&str,update:&[u8])->CatalogResult<()>{self.stage_suggestion_accept_update_authorized(slug,comment_id,request_id,request_digest,update,AnnotationAuthority::default())}
    pub fn stage_suggestion_accept_update_authorized(&self,slug:&str,comment_id:&str,request_id:&str,request_digest:&str,update:&[u8],authority:AnnotationAuthority<'_>)->CatalogResult<()>{if update.is_empty(){return Err(CatalogError::Invalid("invalid suggestion acceptance update".into()))}self.immediate(|tx|{annotation_session_active(tx,authority)?;let doc=document_id(tx,slug)?;let plan=serde_json::json!({"version":1,"commentId":comment_id,"update":hex::encode(update)}).to_string();let n=tx.execute("UPDATE operations SET plan_json=?1,updated_at=max(updated_at,?2) WHERE document_id=?3 AND actor_key=?4 AND request_key=?5 AND request_digest=?6 AND state='prepared'",params![plan,unix_millis(),doc,format!("annotation:{comment_id}"),request_id,request_digest]).map_err(CatalogError::from)?;if n==1{Ok(())}else{Err(CatalogError::Conflict("suggestion acceptance receipt is no longer prepared".into()))}})}
    pub fn suggestion_accept_update(&self,slug:&str,request_id:&str,request_digest:&str)->CatalogResult<Option<Vec<u8>>>{self.with_connection(|c|{let doc=document_id_connection(c,slug)?;let plan:Option<String>=c.query_row("SELECT plan_json FROM operations WHERE document_id=?1 AND request_key=?2 AND request_digest=?3 AND kind='agent_annotations' AND state='prepared'",params![doc,request_id,request_digest],|r|r.get(0)).optional().map_err(CatalogError::from)?;let Some(plan)=plan else{return Ok(None)};let v:serde_json::Value=serde_json::from_str(&plan).map_err(|_|CatalogError::Invalid("invalid acceptance plan".into()))?;v.get("update").and_then(|v|v.as_str()).map(hex::decode).transpose().map_err(|e|CatalogError::Invalid(format!("invalid acceptance update: {e}")))})}
    pub fn pending_suggestion_accept(&self,slug:&str,comment_id:&str)->CatalogResult<bool>{self.with_connection(|c|{let doc=document_id_connection(c,slug)?;c.query_row("SELECT EXISTS(SELECT 1 FROM operations WHERE document_id=?1 AND actor_key=?2 AND kind='agent_annotations' AND state='prepared')",params![doc,format!("annotation:{comment_id}")],|r|r.get(0)).map_err(CatalogError::from)})}
    pub fn suggestion_accept_checkpoint(&self,slug:&str,request_id:&str,request_digest:&str)->CatalogResult<Option<(String,String,String)>>{self.with_connection(|c|{let doc=document_id_connection(c,slug)?;let result:Option<String>=c.query_row("SELECT result_json FROM operations WHERE document_id=?1 AND request_key=?2 AND request_digest=?3 AND kind='agent_annotations' AND state='prepared'",params![doc,request_id,request_digest],|r|r.get(0)).optional().map_err(CatalogError::from)?;let Some(result)=result else{return Ok(None)};let v:serde_json::Value=serde_json::from_str(&result).map_err(|_|CatalogError::Invalid("invalid acceptance result".into()))?;Ok(Some((v.get("commentId").and_then(|v|v.as_str()).unwrap_or_default().into(),v.get("resolvedIn").and_then(|v|v.as_str()).unwrap_or_default().into(),v.get("resolvedAt").and_then(|v|v.as_str()).unwrap_or_default().into())))})}
    pub fn finish_suggestion_accept(&self,slug:&str,comment_id:&str,request_id:&str,request_digest:&str,resolved_in:&str,resolved_at:&str)->CatalogResult<Comment>{self.immediate(|tx|{let doc=document_id(tx,slug)?;let op:Option<(String,String,String)>=tx.query_row("SELECT id,state,request_digest FROM operations WHERE document_id=?1 AND actor_key=?2 AND request_key=?3",params![doc,format!("annotation:{comment_id}"),request_id],|r|Ok((r.get(0)?,r.get(1)?,r.get(2)?))).optional().map_err(CatalogError::from)?;let Some((op,state,digest))=op else{return Err(CatalogError::NotFound)};if digest!=request_digest{return Err(CatalogError::Conflict("suggestion acceptance receipt does not match".into()))}if state=="committed"{return Self::comment_in_tx(tx,slug,comment_id)}if state!="prepared"{return Err(CatalogError::Conflict("suggestion acceptance was aborted".into()))}let at=millis(resolved_at);let n=tx.execute("UPDATE annotations SET suggestion_state='accepted',acceptance_operation_id=?1,resolution_revision=?2,resolved_at=?3,updated_at=?3 WHERE document_id=?4 AND id=?5 AND kind='suggestion'",params![op,resolved_in,at,doc,comment_id]).map_err(CatalogError::from)?;if n!=1{return Err(CatalogError::NotFound)}let done=unix_millis();let result=serde_json::json!({"version":1,"commentId":comment_id,"resolvedIn":resolved_in,"resolvedAt":resolved_at}).to_string();tx.execute("UPDATE operations SET state='committed',result_json=?1,completed_at=?2,receipt_expires_at=?3,updated_at=?2 WHERE id=?4 AND state='prepared'",params![result,done,done.saturating_add(7*24*60*60*1000),op]).map_err(CatalogError::from)?;Self::comment_in_tx(tx,slug,comment_id)})}

    pub fn delete_comment(&self,slug:&str,id:&str)->CatalogResult<bool>{self.delete_comment_authorized(slug,id,AnnotationAuthority::default())}
    pub fn delete_comment_authorized(&self,slug:&str,id:&str,authority:AnnotationAuthority<'_>)->CatalogResult<bool>{self.immediate(|tx|{annotation_session_active(tx,authority)?;let doc=document_id(tx,slug)?;Ok(tx.execute("DELETE FROM annotations WHERE document_id=?1 AND id=?2",params![doc,id]).map_err(CatalogError::from)?==1)})}
    pub fn delete_reply(&self,slug:&str,comment_id:&str,id:&str)->CatalogResult<bool>{self.immediate(|tx|{let doc=document_id(tx,slug)?;Ok(tx.execute("DELETE FROM replies WHERE document_id=?1 AND annotation_id=?2 AND id=?3",params![doc,comment_id,id]).map_err(CatalogError::from)?==1)})}
    pub(super) fn comment_in_tx(tx:&Transaction<'_>,slug:&str,id:&str)->CatalogResult<Comment>{let mut s=tx.prepare(&format!("{COMMENT_SELECT} WHERE d.slug=?1 AND a.id=?2")).map_err(CatalogError::from)?;s.query_row(params![slug,id],Self::read_comment).map_err(CatalogError::from)}
    pub(super) fn read_comment(r:&rusqlite::Row<'_>)->rusqlite::Result<Comment>{Ok(Comment{slug:r.get(0)?,id:r.get(1)?,seq:r.get(2)?,motivation:r.get(3)?,body:r.get(4)?,creator:r.get(5)?,author:r.get(6)?,via:r.get(7)?,created:timestamp(r.get::<_,i64>(8)?),publication_id:r.get(9)?,exact:r.get(10)?,prefix:r.get(11)?,suffix:r.get(12)?,position:r.get(13)?,region:r.get(14)?,quarto_output:r.get(15)?,source_path:r.get(16)?,source_exact:r.get(17)?,source_prefix:r.get(18)?,source_suffix:r.get(19)?,source_position:r.get(20)?,proposed:r.get(21)?,pass:r.get(25)?,outcome:r.get(22)?,accept_request:r.get(23)?,revision:r.get(24)?,resolved:r.get(26)?,resolved_at:r.get::<_,Option<i64>>(27)?.map(timestamp),resolved_in:r.get(28)?,point:r.get::<_,i64>(29)?!=0,color:r.get(30)?})}
    pub fn insert_reply(&self,reply:&Reply)->CatalogResult<Reply>{self.insert_reply_authorized(reply,AnnotationAuthority::default())}
    fn insert_reply_authorized(&self,reply:&Reply,authority:AnnotationAuthority<'_>)->CatalogResult<Reply>{if reply.body.len()>65_536||reply.id.is_empty(){return Err(CatalogError::Invalid("invalid reply".into()))}self.immediate(|tx|{annotation_session_active(tx,authority)?;let doc=document_id(tx,&reply.slug)?;let exists:i64=tx.query_row("SELECT count(*) FROM annotations WHERE document_id=?1 AND id=?2",params![doc,reply.comment_id],|r|r.get(0)).map_err(CatalogError::from)?;if exists!=1{return Err(CatalogError::NotFound)}let count:i64=tx.query_row("SELECT count(*) FROM replies WHERE document_id=?1 AND annotation_id=?2",params![doc,reply.comment_id],|r|r.get(0)).map_err(CatalogError::from)?;if count>=100{return Err(CatalogError::Conflict("reply limit reached".into()))}let at=millis(&reply.created);tx.execute("INSERT INTO replies(document_id,annotation_id,id,body,author_account_id,author_key,author_label,created_at,updated_at) VALUES(?1,?2,?3,?4,?5,?6,?7,?8,?8)",params![doc,reply.comment_id,reply.id,reply.body,(!authority.account_id.is_empty()).then_some(authority.account_id),reply.creator,reply.author,at]).map_err(CatalogError::from)?;Ok(reply.clone())})}
    pub fn insert_reply_request(&self,reply:&Reply,_request_id:&str,_request_digest:&str,_created_at:i64)->CatalogResult<Reply>{self.insert_reply(reply)}
    pub fn insert_reply_request_authorized(&self,reply:&Reply,_request_id:&str,_request_digest:&str,_created_at:i64,authority:AnnotationAuthority<'_>)->CatalogResult<Reply>{self.insert_reply_authorized(reply,authority)}
    pub fn update_reply(&self,reply:&Reply)->CatalogResult<Reply>{self.immediate(|tx|{let doc=document_id(tx,&reply.slug)?;let at=millis(&reply.created);let n=tx.execute("UPDATE replies SET body=?4,author_key=?5,author_label=?6,updated_at=?7 WHERE document_id=?1 AND annotation_id=?2 AND id=?3",params![doc,reply.comment_id,reply.id,reply.body,reply.creator,reply.author,at]).map_err(CatalogError::from)?;if n==1{Ok(reply.clone())}else{Err(CatalogError::NotFound)}})}
    pub fn replies(&self,slug:&str,comment_id:&str,limit:u32)->CatalogResult<Vec<Reply>>{let limit=i64::from(limit.clamp(1,100));self.with_connection(|c|{let doc=document_id_connection(c,slug)?;let mut s=c.prepare("SELECT ?1,annotation_id,id,body,author_key,author_label,created_at FROM replies WHERE document_id=?2 AND annotation_id=?3 ORDER BY created_at,id LIMIT ?4").map_err(CatalogError::from)?;let mut rows=s.query(params![slug,doc,comment_id,limit]).map_err(CatalogError::from)?;let mut out=Vec::new();while let Some(r)=rows.next().map_err(CatalogError::from)?{out.push(Reply{slug:r.get(0)?,comment_id:r.get(1)?,id:r.get(2)?,body:r.get(3)?,creator:r.get(4)?,author:r.get(5)?,created:timestamp(r.get::<_,i64>(6)?)});}Ok(out)})}
}
