//! Bounded lifecycle work over simple document prefixes.

use std::collections::HashSet;
use std::sync::Arc;
use time::Duration;

use super::blob::BlobStore;
use super::postgres::PostgresCatalog;

/// How long a deleted document stays in the trash before it is purged.
/// Derived state, not a queue row: `documents.deleted_at` plus this is when
/// the background worker may take it (§8.6).
pub const DELETION_GRACE: Duration = Duration::days(7);

pub struct Maintenance {
    catalog: Arc<PostgresCatalog>,
    blobs: Arc<dyn BlobStore>,
}

impl Maintenance {
    pub fn new(catalog: Arc<PostgresCatalog>, blobs: Arc<dyn BlobStore>) -> Self {
        Self { catalog, blobs }
    }

    pub async fn delete_superseded_bases(&self, batch: i64) -> Result<usize, String> {
        if !(1..=500).contains(&batch) {
            return Err("base cleanup batch must be 1..=500".into());
        }
        let keys = sqlx::query_scalar!(
            "SELECT snapshot_key FROM superseded_bases WHERE delete_after<=now()
             ORDER BY delete_after LIMIT $1",
            batch,
        )
        .fetch_all(self.catalog.pool())
        .await
        .map_err(|e| e.to_string())?;
        let mut removed = 0;
        let mut failures = Vec::new();
        for key in keys {
            match self.blobs.delete(std::slice::from_ref(&key)).await {
                Ok(()) => {
                    // The row goes only after the bytes do, so a failed
                    // delete is retried rather than forgotten.
                    removed +=
                        sqlx::query!("DELETE FROM superseded_bases WHERE snapshot_key=$1", key,)
                            .execute(self.catalog.pool())
                            .await
                            .map_err(|error| error.to_string())?
                            .rows_affected() as usize;
                }
                Err(error) => failures.push(format!("{key}: {error}")),
            }
        }
        if failures.is_empty() {
            Ok(removed)
        } else {
            Err(format!(
                "failed to delete {} superseded base(s): {}",
                failures.len(),
                failures.join("; ")
            ))
        }
    }

    pub async fn delete_orphans(&self, batch: usize, grace: Duration) -> Result<usize, String> {
        if !(1..=1000).contains(&batch) || grace < Duration::days(7) {
            return Err("orphan cleanup bounds are invalid".into());
        }
        let mut removed = 0;
        for (name, prefix, retention) in [
            ("document_objects", "documents/", grace),
            // Agent views, candidates, admissions and render receipts are
            // unusable after at most one hour. Keep one further hour for
            // in-flight requests and clock skew, without retaining full source
            // snapshots for the general seven-day orphan window.
            (
                "temporary_agent_objects",
                "temporary/agent/",
                Duration::hours(2),
            ),
            ("temporary_objects", "temporary/", grace),
        ] {
            // Where the last pass stopped, kept in the deployment's own
            // runtime state rather than a table of its own: it is one string
            // per prefix, it is regenerated by the next pass if it is lost,
            // and a table whose whole contents are three rows is a table
            // nobody remembers to look at.
            let cursor: Option<String> = self
                .catalog
                .runtime_state(&format!("sweep.{name}"))
                .await
                .map_err(|error| error.to_string())?
                .and_then(|value| value.as_str().map(str::to_string));
            let page = self
                .blobs
                .list_page(prefix, cursor.as_deref(), batch)
                .await
                .map_err(|error| error.to_string())?;
            let keys: Vec<String> = page.iter().map(|item| item.key.clone()).collect();
            let referenced = if prefix == "documents/" {
                referenced_keys(self.catalog.as_ref(), &keys).await?
            } else {
                HashSet::new()
            };
            let cutoff = std::time::SystemTime::now()
                .checked_sub(retention.unsigned_abs())
                .ok_or("orphan cleanup grace is outside the system clock range")?;
            let doomed: Vec<String> = page
                .iter()
                .filter(|item| !referenced.contains(&item.key))
                .filter(|item| item.modified_at.is_some_and(|created| created <= cutoff))
                .map(|item| item.key.clone())
                .collect();
            if !doomed.is_empty() {
                self.blobs
                    .delete(&doomed)
                    .await
                    .map_err(|error| error.to_string())?;
                removed += doomed.len();
            }
            let next = if page.len() < batch {
                None
            } else {
                keys.last().cloned()
            };
            self.catalog
                .set_runtime_state(
                    &format!("sweep.{name}"),
                    match next {
                        Some(key) => serde_json::Value::String(key),
                        None => serde_json::Value::Null,
                    },
                )
                .await
                .map_err(|error| error.to_string())?;
        }
        Ok(removed)
    }
}

async fn referenced_keys(
    catalog: &PostgresCatalog,
    keys: &[String],
) -> Result<HashSet<String>, String> {
    if keys.is_empty() {
        return Ok(HashSet::new());
    }
    // Four tables name a blob now: assets, label archives, the live
    // compaction base and the bases still inside their seven-day grace. The
    // last one is not optional: a superseded base is still being read, so a
    // sweep that did not know about it would delete bytes out from under a
    // reader. That list is the same one the backup enumerator reads, and the
    // two are changed together (§8.5).
    let found = sqlx::query_scalar!(
        r#"SELECT storage_key AS "key!" FROM document_assets WHERE storage_key=ANY($1)
           UNION SELECT archive_key FROM document_labels WHERE archive_key=ANY($1)
           UNION SELECT snapshot_key FROM document_bases WHERE snapshot_key=ANY($1)
           UNION SELECT snapshot_key FROM superseded_bases WHERE snapshot_key=ANY($1)"#,
        keys,
    )
    .fetch_all(catalog.pool())
    .await
    .map_err(|error| error.to_string())?;
    Ok(found.into_iter().collect())
}
