//! Family names typst gives by PostScript name, overriding the name table.
//! Generated from typst-library 0.15.1 `src/text/font/exceptions.rs`, the
//! entries that set a family, sorted bytewise for binary search:
//!
//! ```sh
//! tr '\n' ' ' < exceptions.rs | grep -oE '"[^"]+" => Exception::new\(\)[^,]*' \
//!   | grep 'family(' | sed -E 's/^"([^"]*)".*\.family\("([^"]*)"\).*/    ("\1", "\2"),/' \
//!   | LC_ALL=C sort
//! ```
//!
//! `families_in_matches_typst_output` in `fonts.rs` holds the result to the
//! compiler; regenerate this when the typst dev-dependency moves.

pub fn find_exception(postscript_name: &str) -> Option<&'static str> {
    EXCEPTION_MAP
        .binary_search_by_key(&postscript_name, |(ps, _)| *ps)
        .ok()
        .map(|idx| EXCEPTION_MAP[idx].1)
}

const EXCEPTION_MAP: &[(&str, &str)] = &[
    ("ArchivoNarrow-Bold", "Archivo Narrow"),
    ("ArchivoNarrow-BoldItalic", "Archivo Narrow"),
    ("ArchivoNarrow-Italic", "Archivo Narrow"),
    ("ArchivoNarrow-Regular", "Archivo Narrow"),
    ("LMMono12-Regular", "Latin Modern Mono 12"),
    ("LMMono8-Regular", "Latin Modern Mono 8"),
    ("LMMono9-Regular", "Latin Modern Mono 9"),
    ("LMRoman12-Bold", "Latin Modern Roman 12"),
    ("LMRoman12-Italic", "Latin Modern Roman 12"),
    ("LMRoman12-Regular", "Latin Modern Roman 12"),
    ("LMRoman17-Regular", "Latin Modern Roman 17"),
    ("LMRoman5-Bold", "Latin Modern Roman 5"),
    ("LMRoman5-Regular", "Latin Modern Roman 5"),
    ("LMRoman6-Bold", "Latin Modern Roman 6"),
    ("LMRoman6-Regular", "Latin Modern Roman 6"),
    ("LMRoman7-Bold", "Latin Modern Roman 7"),
    ("LMRoman7-Italic", "Latin Modern Roman 7"),
    ("LMRoman7-Regular", "Latin Modern Roman 7"),
    ("LMRoman8-Bold", "Latin Modern Roman 8"),
    ("LMRoman8-Italic", "Latin Modern Roman 8"),
    ("LMRoman8-Regular", "Latin Modern Roman 8"),
    ("LMRoman9-Bold", "Latin Modern Roman 9"),
    ("LMRoman9-Italic", "Latin Modern Roman 9"),
    ("LMRoman9-Regular", "Latin Modern Roman 9"),
    ("LMRomanSlant12-Regular", "Latin Modern Roman 12"),
    ("LMRomanSlant17-Regular", "Latin Modern Roman 17"),
    ("LMRomanSlant8-Regular", "Latin Modern Roman 8"),
    ("LMRomanSlant9-Regular", "Latin Modern Roman 9"),
    ("LMSans12-Oblique", "Latin Modern Sans 12"),
    ("LMSans12-Regular", "Latin Modern Sans 12"),
    ("LMSans17-Oblique", "Latin Modern Sans 17"),
    ("LMSans17-Regular", "Latin Modern Sans 17"),
    ("LMSans8-Oblique", "Latin Modern Sans 8"),
    ("LMSans8-Regular", "Latin Modern Sans 8"),
    ("LMSans9-Oblique", "Latin Modern Sans 9"),
    ("LMSans9-Regular", "Latin Modern Sans 9"),
    ("NewCM08-Book", "New Computer Modern 08"),
    ("NewCM08-BookItalic", "New Computer Modern 08"),
    ("NewCM08-Italic", "New Computer Modern 08"),
    ("NewCM08-Regular", "New Computer Modern 08"),
    ("NewCM10-Bold", "New Computer Modern"),
    ("NewCM10-BoldItalic", "New Computer Modern"),
    ("NewCM10-Book", "New Computer Modern"),
    ("NewCM10-BookItalic", "New Computer Modern"),
    ("NewCM10-Italic", "New Computer Modern"),
    ("NewCM10-Regular", "New Computer Modern"),
    ("NewCMMath-Bold", "New Computer Modern Math"),
    ("NewCMMath-Book", "New Computer Modern Math"),
    ("NewCMMath-Regular", "New Computer Modern Math"),
    ("NewCMMono10-Bold", "New Computer Modern Mono"),
    ("NewCMMono10-BoldOblique", "New Computer Modern Mono"),
    ("NewCMMono10-Book", "New Computer Modern Mono"),
    ("NewCMMono10-BookItalic", "New Computer Modern Mono"),
    ("NewCMMono10-Italic", "New Computer Modern Mono"),
    ("NewCMMono10-Regular", "New Computer Modern Mono"),
    ("NewCMSans08-Book", "New Computer Modern Sans 08"),
    ("NewCMSans08-BookOblique", "New Computer Modern Sans 08"),
    ("NewCMSans08-Oblique", "New Computer Modern Sans 08"),
    ("NewCMSans08-Regular", "New Computer Modern Sans 08"),
    ("NewCMSans10-Bold", "New Computer Modern Sans"),
    ("NewCMSans10-BoldOblique", "New Computer Modern Sans"),
    ("NewCMSans10-Book", "New Computer Modern Sans"),
    ("NewCMSans10-BookOblique", "New Computer Modern Sans"),
    ("NewCMSans10-Oblique", "New Computer Modern Sans"),
    ("NewCMSans10-Regular", "New Computer Modern Sans"),
    ("NewCMSansMath-Regular", "New Computer Modern Sans Math"),
    ("NewCMUncial08-Bold", "New Computer Modern Uncial 08"),
    ("NewCMUncial08-Book", "New Computer Modern Uncial 08"),
    ("NewCMUncial08-Regular", "New Computer Modern Uncial 08"),
    ("NewCMUncial10-Bold", "New Computer Modern Uncial"),
    ("NewCMUncial10-Book", "New Computer Modern Uncial"),
    ("NewCMUncial10-Regular", "New Computer Modern Uncial"),
    ("NotoNaskhArabicUISemi-Bold", "Noto Naskh Arabic UI"),
    ("NotoSans-DisplayBlackItalic", "Noto Sans Display"),
    ("NotoSans-DisplayCondensedBlackItalic", "Noto Sans Display"),
    ("NotoSans-DisplayCondensedBold", "Noto Sans Display"),
    ("NotoSans-DisplayCondensedBoldItalic", "Noto Sans Display"),
    ("NotoSans-DisplayCondensedExtraBoldItalic", "Noto Sans Display"),
    ("NotoSans-DisplayCondensedExtraLightItalic", "Noto Sans Display"),
    ("NotoSans-DisplayCondensedItalic", "Noto Sans Display"),
    ("NotoSans-DisplayCondensedLightItalic", "Noto Sans Display"),
    ("NotoSans-DisplayCondensedMediumItalic", "Noto Sans Display"),
    ("NotoSans-DisplayCondensedSemiBoldItalic", "Noto Sans Display"),
    ("NotoSans-DisplayCondensedThinItalic", "Noto Sans Display"),
    ("NotoSans-DisplayExtraBoldItalic", "Noto Sans Display"),
    ("NotoSans-DisplayExtraCondensedBlackItalic", "Noto Sans Display"),
    ("NotoSans-DisplayExtraCondensedBold", "Noto Sans Display"),
    ("NotoSans-DisplayExtraCondensedBoldItalic", "Noto Sans Display"),
    ("NotoSans-DisplayExtraCondensedExtraBoldItalic", "Noto Sans Display"),
    ("NotoSans-DisplayExtraCondensedExtraLightItalic", "Noto Sans Display"),
    ("NotoSans-DisplayExtraCondensedItalic", "Noto Sans Display"),
    ("NotoSans-DisplayExtraCondensedLightItalic", "Noto Sans Display"),
    ("NotoSans-DisplayExtraCondensedMediumItalic", "Noto Sans Display"),
    ("NotoSans-DisplayExtraCondensedSemiBoldItalic", "Noto Sans Display"),
    ("NotoSans-DisplayExtraCondensedThinItalic", "Noto Sans Display"),
    ("NotoSans-DisplayExtraLightItalic", "Noto Sans Display"),
    ("NotoSans-DisplayLightItalic", "Noto Sans Display"),
    ("NotoSans-DisplayMediumItalic", "Noto Sans Display"),
    ("NotoSans-DisplaySemiBoldItalic", "Noto Sans Display"),
    ("NotoSans-DisplaySemiCondensedBlackItalic", "Noto Sans Display"),
    ("NotoSans-DisplaySemiCondensedBold", "Noto Sans Display"),
    ("NotoSans-DisplaySemiCondensedBoldItalic", "Noto Sans Display"),
    ("NotoSans-DisplaySemiCondensedExtraBoldItalic", "Noto Sans Display"),
    ("NotoSans-DisplaySemiCondensedExtraLightItalic", "Noto Sans Display"),
    ("NotoSans-DisplaySemiCondensedItalic", "Noto Sans Display"),
    ("NotoSans-DisplaySemiCondensedLightItalic", "Noto Sans Display"),
    ("NotoSans-DisplaySemiCondensedMediumItalic", "Noto Sans Display"),
    ("NotoSans-DisplaySemiCondensedSemiBoldItalic", "Noto Sans Display"),
    ("NotoSans-DisplaySemiCondensedThinItalic", "Noto Sans Display"),
    ("NotoSans-DisplayThinItalic", "Noto Sans Display"),
    ("NotoSansSoraSompengSemi-Bold", "Noto Sans Sora Sompeng"),
    ("NotoSerif-DisplayCondensedBold", "Noto Serif Display"),
    ("NotoSerif-DisplayExtraCondensedBold", "Noto Serif Display"),
    ("NotoSerif-DisplaySemiCondensedBold", "Noto Serif Display"),
    ("SimSun-ExtB", "SimSun-ExtB"),
];
