import assert from "node:assert/strict";
import * as Y from "yjs";
import { join } from "../../src/lib/collab.js";
import { checkPlacement, fileTree, folderPaths, droppedFiles } from "../../src/lib/file-manager.js";
import { zip } from "../../src/lib/zip.js";
const rules = { text_extensions: [".tex", ".bib", ".md"], asset_extensions: [".png"], max_path: 200 };
const session = join({ send() {}, mayEdit: true });
const peer = join({ send() {}, mayEdit: true });
try {
  const main = session.addText("main.tex", "main");
  session.setMain(main);
  const chapter = session.addText("chapters/one.tex", "original");
  session.putAsset("chapters/fig/chart.png", "digest");
  session.addFolder("chapters/empty", rules);
  session.addFolder("archive", rules);
  const folder = { kind: "folder", id: "chapters", path: "chapters" };
  assert.throws(() => session.relocate([folder], "chapters/sub", rules), /inside itself/);
  session.addText("archive/one.tex", "collision");
  const before = session.tree();
  assert.throws(() => session.relocate([session.list().find((file) => file.id === chapter)], "archive", rules), /already/);
  assert.deepEqual(session.tree(), before, "failed move changes nothing");
  const update = Y.encodeStateAsUpdate(session.doc);
  Y.applyUpdate(peer.doc, update);
  const peerVector = Y.encodeStateVector(peer.doc);
  peer.textOf(chapter).insert(0, "REMOTE ");
  let updates = 0;
  const count = () => updates++;
  session.doc.on("update", count);
  session.relocate([folder, session.list().find((file) => file.id === chapter)], "archive", rules);
  session.doc.off("update", count);
  assert.equal(updates, 1, "folder move is a single Yjs transaction");
  Y.applyUpdate(session.doc, Y.encodeStateAsUpdate(peer.doc, peerVector));
  Y.applyUpdate(peer.doc, Y.encodeStateAsUpdate(session.doc));
  assert.equal(session.textOf(chapter).toString(), "REMOTE original");
  assert.equal(session.paths.get(chapter), "archive/chapters/one.tex");
  assert.deepEqual(peer.folders(), session.folders(), "empty directories synchronize");
  assert.ok(session.folders().includes("archive/chapters/empty"));
  assert.equal(session.tree().digests["archive/chapters/fig/chart.png"], "digest");
  const tree = fileTree(session.list(), session.folders());
  assert.equal(tree.children[0].kind, "folder");
  assert.throws(() => session.addFolder("../escape", rules), /climb/);
  assert.throws(() => session.addFolder("main.tex", rules), /already/);
  assert.throws(() => session.addFolder("main.tex/sub", rules), /cannot contain/);
  assert.throws(() => checkPlacement(rules, { kind: "text", path: "archive/chapters.tex" }, [{ kind: "text", path: "archive/chapters.tex/one.tex" }], []), /already/);
  assert.throws(() => session.relocate([session.list().find((file) => file.id === main)], "main.png", rules, true), /cannot change/);
  assert.throws(() => session.removeEntries([session.list().find((file) => file.id === main)]), /main file/);
  const copy = session.duplicateEntry(session.list().find((file) => file.id === chapter), "copied.tex", rules);
  session.textOf(copy).insert(0, "COPY ");
  assert.equal(session.textOf(chapter).toString(), "REMOTE original", "duplicate has independent text");
  const stale = session.list().find((file) => file.id === copy);
  session.renameFile(copy, "new-copy.tex", "text");
  assert.throws(() => session.removeEntries([stale]), /changed or was removed/);
  session.removeEntries([{ kind: "folder", id: "archive/chapters", path: "archive/chapters" }]);
  assert.equal(session.textOf(chapter), null);
  assert.ok(session.folders().includes("archive"), "removing last child preserves its parent");
  assert.ok(!folderPaths(session.list(), session.folders()).includes("archive/chapters"));
  const blob = zip({ "empty/": new Uint8Array(), "main.tex": "body" });
  const bytes = new Uint8Array(await blob.arrayBuffer());
  const view = new DataView(bytes.buffer);
  const central = bytes.findIndex((_, i) => i + 4 < bytes.length && view.getUint32(i, true) === 0x02014b50);
  assert.equal(view.getUint32(central + 38, true), 0x10, "ZIP marks empty folders as directories");
  const read = await droppedFiles({ items: [], files: [{ name: "main.tex" }] });
  assert.equal(read.files[0].path, "main.tex");
  const directory = (name, batches) => ({ name, isDirectory: true, createReader: () => ({ readEntries: (done) => done(batches.shift() || []) }) });
  const incoming = await droppedFiles({ files: [], items: [{ kind: "file", webkitGetAsEntry: () => directory("paper", [
    [{ name: "main.tex", isFile: true, file: (done) => done({ name: "main.tex" }) }],
    [directory("empty", [])],
  ]) }] });
  assert.deepEqual(incoming.folders, ["paper", "paper/empty"]);
  assert.equal(incoming.files[0].path, "paper/main.tex", "directory uploads consume every browser batch");
  console.log("file-manager: atomic moves, collaborative edits, empty folders, collision protection, deletion, duplication and ZIP passed");
} finally { session.leave(); peer.leave(); }
