#!/usr/bin/env bash
set -euo pipefail

: "${SCOOP_BUCKET_GITHUB_TOKEN:?SCOOP_BUCKET_GITHUB_TOKEN is required}"

tag="${LIBREPAPER_RELEASE_TAG:-${GITHUB_REF_NAME:-}}"
if [[ ! "${tag}" =~ ^v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$ ]]; then
  echo "expected a stable v-prefixed semver release tag, got: ${tag:-<empty>}" >&2
  exit 1
fi

version="${tag#v}"
archive="librepaper-x86_64-pc-windows-msvc.zip"
release_url="https://github.com/LibrePaper/librepaper/releases/download/${tag}"
tmpdir="$(mktemp -d)"
trap 'rm -rf "${tmpdir}"' EXIT

curl -fsSL "${release_url}/${archive}" -o "${tmpdir}/${archive}"
curl -fsSL "${release_url}/${archive}.sha256" -o "${tmpdir}/${archive}.sha256"
declared="$(awk 'NR == 1 { print $1 }' "${tmpdir}/${archive}.sha256")"
if ! [[ "${declared}" =~ ^[[:xdigit:]]{64}$ ]]; then
  echo "invalid SHA-256 checksum for ${archive}" >&2
  exit 1
fi
if command -v sha256sum >/dev/null 2>&1; then
  actual="$(sha256sum "${tmpdir}/${archive}" | awk '{print $1}')"
else
  actual="$(shasum -a 256 "${tmpdir}/${archive}" | awk '{print $1}')"
fi
if [[ "${actual,,}" != "${declared,,}" ]]; then
  echo "SHA-256 mismatch for ${archive}" >&2
  exit 1
fi

export GIT_CONFIG_COUNT=1
export GIT_CONFIG_KEY_0=http.https://github.com/.extraheader
export GIT_CONFIG_VALUE_0="AUTHORIZATION: basic $(printf 'x-access-token:%s' "${SCOOP_BUCKET_GITHUB_TOKEN}" | base64 | tr -d '\n')"
bucket_dir="${tmpdir}/scoop-bucket"
git clone https://github.com/vincentarelbundock/scoop-bucket.git "${bucket_dir}"
cd "${bucket_dir}"

mkdir -p bucket
cat > bucket/librepaper.json <<MANIFEST
{
    "##": "This file is generated by LibrePaper's release workflow. DO NOT EDIT.",
    "version": "${version}",
    "description": "Browser based document collaboration and review companion",
    "homepage": "https://github.com/LibrePaper/librepaper",
    "license": "MIT",
    "architecture": {
        "64bit": {
            "url": "${release_url}/${archive}",
            "hash": "${actual}"
        }
    },
    "bin": "librepaper.exe",
    "checkver": {
        "github": "https://github.com/LibrePaper/librepaper"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/LibrePaper/librepaper/releases/download/v\$version/${archive}"
            }
        },
        "hash": {
            "url": "\$url.sha256"
        }
    },
    "notes": [
        "LibrePaper's Windows companion is installed as librepaper.exe. Start it with: librepaper",
        "Upgrade with: scoop update librepaper"
    ]
}
MANIFEST

git add bucket/librepaper.json
if git diff --cached --quiet; then
  echo "Scoop manifest already up to date"
  exit 0
fi

git config user.name "github-actions[bot]"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
git commit -m "Update librepaper manifest to ${tag}"
git push origin HEAD:main
